### ISSUE TITLE
Got error on installing package

### ISSUE THREAD

**Issue by yogakurniawan** [jaredpalmer/after.js#10]
Hi @jaredpalmer ,

I love this library so much by reading the philosophy / project goals, I was wondering, it would be amazing if next.js had react-router v4 as its routing system rather than dealing with project structure. now this is really happening.

I got a little problem on installing this package.
I use this script as in readme

> npm i @jaredpalmer/after react-router-dom react-dom --save

then I got this error

> npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@jaredpalmer/after" "react-router-dom" "react-dom" "--save"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code E404
npm ERR! 404 Not found : jaredpalmer/after
npm ERR! 404
npm ERR! 404  jaredpalmer/after is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! Please include the following file with any support request:
npm ERR!     D:\EXPERIMENT\REACT\after-app\npm-debug.log

Could you please help me?

Thank you

**Comment by jaredpalmer** [comment]
Fixed a bunch of stuff. Try installing now `yarn add @jaredpalmer/after@0.3.0 `
