### ISSUE TITLE
Discussion: Render Blocking Flag

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/after.js#11]
Although I prefer to set `state.data` to `undefined` during page changes (which allows for an easy way to writing a loading indicator), some users may want to keep existing state present. We could potentially accomplish this with a flag. 

Thoughts?

**Comment by BrunoScheufler** [comment]
I think a flag for the transition period would be a good idea because it wouldn't mutate the state while changing, and a flag could also be easily used for a loading indicator for example, IMO.
