### ISSUE TITLE
Next.js vs. After.js

### ISSUE THREAD

**Issue by rockmandash** [jaredpalmer/after.js#110]
To be honest, which is better?

**Comment by jaredpalmer** [comment]
If ya have to ask....

**Comment by rockmandash** [comment]
Asked bad question.
Feels so sorry.

**Comment by jaydenseric** [comment]
@rockmandash don't feel too bad, it's a legitimate question that everyone who finds this project wonders.

A breakdown of differences between Next.js and After.js would be pretty helpful for migrating over. Also more people would be willing to try After.js out if they knew they weren't going to get blocked by a particular absent feature.

It's not perceived to be negative or adversarial when Inferno and Preact explain in detail how they're different to React.
