### ISSUE TITLE
Beware: v1.2.0 breaks my build + demo

### ISSUE THREAD

**Issue by darcyturk** [jaredpalmer/after.js#112]
Just spent almost all night trying to figure out why this damn thing wasn't working and when I reset it back to 1.1.0 in package.json, all is restored + well with the world again! So maybe make a note? There must be breaking changes in 1.2.0....

**Comment by fdidron** [comment]
@darcyturk I ran into an issue with 1.2.x as well, it seems that the `renderPage` method used in here https://github.com/jaredpalmer/after.js/blob/74cecd9b0c8a724d581fd2dadc0c8c60a7e1e87e/src/Document.tsx#L4 now returns a promise.

My quick fix was to create a custom Document with an async getInitialProps method:

```
static async getInitialProps({ assets, data, renderPage }: any) {
    const page = await renderPage();
    return { assets, data, ...page };
  }
```

@jaredpalmer Is it a valid fix ? If yes I'm happy to send a PR to update Document.tsx as well as Readme.md

**Comment by fdidron** [comment]
@darcyturk Your issue should be fixed upgarding to 1.3.0

**Comment by jaredpalmer** [comment]
1.2 was broken. 1.3 works.

**Comment by jaredpalmer** [comment]
I would suggest everyone also upgrade to Razzle 2 Alpha (Webpack 4).
