### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/after.js#12]

**Comment by jaredpalmer** [comment]
![repo-banner](https://user-images.githubusercontent.com/4060187/34948491-454de294-f9db-11e7-8fc5-86985ba05be8.png)

**Comment by mxstbr** [comment]
> "We need a logo" - 17 minutes ago

> "Here's the finished logo and it's super neat and clean and nice" - 16 minutes ago

Fastest designer on earth 🔥😜
