### ISSUE TITLE
Document renders differently after first load

### ISSUE THREAD

**Issue by krazyjakee** [jaredpalmer/after.js#120]
Material UI has the following instructions for supporting SSR: https://material-ui-next.com/guides/server-rendering/

I can't see how their examples fit in with after as the "renderToString" part is taken care of in the after render method. How can I get material-ui to work with after?

**Comment by Madumo** [comment]
This is how i did to make JSS work:

```tsx
import React, {Component} from 'react';

import {AfterData, AfterRoot} from '@jaredpalmer/after';
import {JssProvider, SheetsRegistry} from 'react-jss'; // 1) Import jss stuff

export class Document extends Component<any, any> {
  public static async getInitialProps({assets, data, renderPage}: any) {
    const sheets = new SheetsRegistry(); // 2) create new sheets registry

    // 3) pass custom renderPage function and wrap the app with JssProvider
    const page = await renderPage((App: React.ComponentType<any>) => (props: any) => (
      <JssProvider registry={sheets}>
        <App {...props} />
      </JssProvider>
    ));

    return {assets, data, sheets, ...page}; // Return sheets with the initial props
  }

  public render() {
    const {helmet, assets, data, sheets} = this.props; // 4) Get sheets from props

    // get attributes from React Helmet
    const htmlAttrs = helmet.htmlAttributes.toComponent();
    const bodyAttrs = helmet.bodyAttributes.toComponent();

    return (
      <html {...htmlAttrs}>
        <head>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta charSet="utf-8" />
          <title>Welcome to the Afterparty</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {helmet.title.toComponent()}
          {helmet.meta.toComponent()}
          {helmet.link.toComponent()}
          {assets.client.css && (
            <link rel="stylesheet" href={assets.client.css} />
          )}
          {/* 6) And finally, render the styles */}
          <style type="text/css">
            {sheets.toString()}
          </style>
        </head>
        <body {...bodyAttrs}>
          <AfterRoot />
          <AfterData data={data} />
          <script
            type="text/javascript"
            src={assets.client.js}
            defer
            crossOrigin="anonymous"
          />
        </body>
      </html>
    );
  }
}
```

**Comment by krazyjakee** [comment]
@Madumo this is progress, I can now see the styles being rendered by the server, however, the class names are not matching up with the client: `Prop `className` did not match. Server: "MuiSvgIconroot-0-2-56" Client: "MuiSvgIcon-root-47"`

**Comment by Madumo** [comment]
Oh, material-ui use a custom className generator. Try this:

```tsx
import React, {Component} from 'react';

import {AfterData, AfterRoot} from '@jaredpalmer/after';
import {JssProvider, SheetsRegistry} from 'react-jss';
import {createGenerateClassName} from 'material-ui/styles'; // Import that
import Layout from 'viking/ui/components/layout';

export class Document extends Component<any, any> {
  public static async getInitialProps({assets, data, renderPage}: any) {
    const sheets = new SheetsRegistry();
    const generateClassName = createGenerateClassName(); // create a className generator
    const page = await renderPage((Page: React.ComponentType<any>) => (props: any) => (
      <JssProvider registry={sheets} generateClassName={generateClassName}> // pass it to JssProvider
        <Layout>
          <Page {...props} />
        </Layout>
      </JssProvider>
    ));
    return {assets, data, sheets, ...page};
  }

  public render() {
    const {helmet, assets, data, sheets} = this.props;
    // get attributes from React Helmet
    const htmlAttrs = helmet.htmlAttributes.toComponent();
    const bodyAttrs = helmet.bodyAttributes.toComponent();

    return (
      <html {...htmlAttrs}>
        <head>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta charSet="utf-8" />
          <title>Welcome to the Afterparty</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {helmet.title.toComponent()}
          {helmet.meta.toComponent()}
          {helmet.link.toComponent()}
          {assets.client.css && (
            <link rel="stylesheet" href={assets.client.css} />
          )}
          <style type="text/css">
            {sheets.toString()}
          </style>
        </head>
        <body {...bodyAttrs}>
          <AfterRoot />
          <AfterData data={data} />
          <script
            type="text/javascript"
            src={assets.client.js}
            defer
            crossOrigin="anonymous"
          />
        </body>
      </html>
    );
  }
}
```

**Comment by krazyjakee** [comment]
@Madumo Thanks for your help on this. I think you're right, this has technically fixed the issue BUT it will only work on the first request after the server has started. Every request after the first returns no styling at all.

**Comment by Madumo** [comment]
@krazyjakee On the material-ui documentation about server-side rendering, they seem to remove the server side renderer style at the first application mount

**Comment by krazyjakee** [comment]
I added the componentDidMount exactly as per their example but it doesn't change anything. Since the sheet and generateClassName are called in the getInitialProps function, I think it's something to do with it behaving differently on subsequent queries. I have taken a look through some of that source but it's over my head.

**Comment by jaredpalmer** [comment]
I would suggest upgrading to Razzle 2 Alpha. This problem appears to be fixed.

**Comment by krazyjakee** [comment]
@jaredpalmer I installed `"razzle": "^2.0.0-alpha.5"` as a devDependency but this issue persists exactly as described above.

**Comment by jaredpalmer** [comment]
I believe the confusion is that _unlike_ Next.js `Document` is not re-used on the client at all. I wonder if we should do something like call renderPage() once on the client too.

**Comment by krazyjakee** [comment]
But ignoring the client, it's the server that is changing the response after the first request. If the server persistently output the styling (as above), then this issue would be resolved.

**Comment by krazyjakee** [comment]
I think I'm getting closer to the source of this issue. In order for afterjs to work with material-ui and react-jss, we need to consider where we call createGenerateClassname.

See the last few comments on https://github.com/mui-org/material-ui/issues/9640

**Comment by oliviertassinari** [comment]
> I believe the confusion is that unlike Next.js Document is not re-used on the client at all.

@jaredpalmer As far as I have used Next.js, `_document.js` is only used server-side. It's never used on the client. 

> This is how i did to make JSS work:

@Madumo Interesting. I never thought of using the server-side generated classes after the reconciliation.

> Subsequent load:

@krazyjakee From what you are describing, I believe that your second request is hitting the cache. You need to reset the `sheetsManager` between two requests. I the future, I want to look into how we can share the stylesheet cache between requests without hitting your issue. From my benchmarks, we can speed up the react rendering speed by 30%.

**Comment by oliviertassinari** [comment]
Also, it would be awesome to have an After.js + Material-UI integration example.

**Comment by krazyjakee** [comment]
@oliviertassinari I'll build a material-ui/afterjs example and do a pull request here if you can help me figure out where and how to reset the sheetsManager between requests 👯.
It's really the last piece of the puzzle, everything else seems fantastic.

**Comment by oliviertassinari** [comment]
> if you can help me figure out where and how to reset the sheetsManager between requests

![capture d ecran 2018-04-04 a 00 14 47](https://user-images.githubusercontent.com/3165635/38278644-369dd290-379d-11e8-9412-40e53e21a3da.png)

`MuiThemeProvider` should be 💯% theme related. I plan on moving the property to a different provider in the future. I have used it as a quick escape hatch to solve the problem in the past. But for now, you can do it like this:
```jsx
<MuiThemeProvider sheetsManager={new Map()}>
```

**Comment by krazyjakee** [comment]
@oliviertassinari it worked! This solved the issue.

**Comment by krazyjakee** [comment]
@oliviertassinari subsequent requests now throw the `Prop `className` did not match. Server: "MuiSvgIcon-root-47" Client: "MuiSvgIcon-root-56` error. Is this a catch-22 situation?

**Comment by nolandg** [comment]
Has this been fixed? I'm getting the same `className` mismatch issue after following the example.

**Comment by nolandg** [comment]
As per MUI's documentation, I think this really boils down to: how do we use the same `generateClassName` on the client and the server for hot reloads? If you look at the error messages closely you see that the `className`s generated on the server are high integers than on the client after hot reloads. This makes sense since I guess `generateClassName` is only operating on a few nodes that got updated and it doesn't count up as high.

Anyone have any thoughts on how to harmonize `generateClassName` for hot reloads?

**Comment by nolandg** [comment]
The best I've achieved now is pretty good but not perfect. Cases that work:

1. First load
2. Reload the browser with no changes to source
3. Changing source in a file that doesn't contain a `withStyles` component and reload browser
4. Changing source in a file that *does* contain a `withStyles` component but *not* reloading browser, ie. just let HMR replace things

What does not work is: changing source in a file containing a `withStyles` component and then reloading the browser. There is a client-side error for `className` mismatch and that offending component loses its styles.

So pretty easy to work around.

**Comment by nolandg** [comment]
Ok, I fixed mine. Accidently had 2 versions of after loaded, one from a peer dep and one from a direct dep. Surprised it worked this well like that. Now with that removed it's absolutely purrrfect. :-)
