### ISSUE TITLE
Razzle Environment variables all end up in the bundle

### ISSUE THREAD

**Issue by krazyjakee** [jaredpalmer/after.js#129]
## Bug, Feature, or Question?

Bug

## Current Behavior

`process.env.RAZZLE_xxx` environment variables are all compiled into the bundle despite not being called in isomorphic code.

## Desired Behavior

Only add environment variable used in isomorphic code to the bundle.

## Suggested Solutions

Sorry, but I don't understand razzle's environment variable logic well enough to suggest anything.

## Additional Information

---

- After.js Version: 1.3.0
- Razzle Version: 2.0.0-alpha.7
- React Version: 16.2.0

**Comment by jaredpalmer** [comment]
This is a Razzle issue. There's discussion about Razzle runtime vars.

**Comment by krazyjakee** [comment]
Here if anyone is interested. https://github.com/jaredpalmer/razzle/issues/528

**Comment by HamidTanhaei** [comment]
if anyone want to use .env variables in runtime, use this little package.
https://www.npmjs.com/package/razzle-plugin-runtimeenv
