### ISSUE TITLE
Redux support for connect with routes

### ISSUE THREAD

**Issue by ragu-S** [jaredpalmer/after.js#131]
## Bug, Feature, or Question?
Bug

## Current Behaviour
Using Redux connect on route components do not get connected on client side due to the server already passing a serialized store object (ie. it tries to read store prop as a real store object, instead of through the context prop).

Normally we would reuse components both on Server and Client, thus connected components are used for both. The issue is that we have to supply a default store property on the server side, in order for the component to be properly connected and using the default store state.

But on client-side because the data object within Afterparty.prototype.render() only has the serialized store property (which was done on the server) when Redux connect() tries to check if store exists within props or context, it tries to read the serialized store property instead of the context.store which is what normally <Provider> passes down by default.

```javascript
// a default connected component that we might have in a common folder, where components are shared between server and client.
class Home extends Component {}

const mapStateToProps = (state, ownProps) => {
  return {
    currentRoute: state.currentRoute
  };
};

const mapDispatchToProps = dispatch => {
  return bindActionCreators(homeActions, dispatch)
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
```

```javascript
const store = configureStore(initialState);

ensureReady(routes).then(data =>
  hydrate(
    <Provider store={store}> 
      <ConnectedRouter history={history}> 
        <After data={data} routes={routes} />
      </ConnectedRouter>
    </Provider>,
    document.getElementById('root')
  )
);
```

## Desired Behaviour
It should read the store state from data and update the client-side store, instead of passing a serialized store property.

## Suggested Solutions
Either on server side, support passing store props via the context prop (currently doesn't work if you attempt to use ```render()```
```javascript
const html = await render({
  req,
  res,
  routes,
  assets,
  context: { store }
  // store <- currently passing just as store prop works server-side but fails client-side as specified above
});
res.send(html);
```

Or perhaps have a way to use the window state reference that can be used when the client-side redux store get initialized, as how it was in Razzle's example.

## Additional Information
- After.js Version: 1.3.0
- Razzle Version: 0.8.14
- React Version: 16.2.0
- OS: Mac OS X
- Node Version: 9.2.1
- Package Manager and Version: npm v5.8.0

**Comment by wiput1999** [comment]
Is it work now?

**Comment by Qolzam** [comment]
@wiput1999 May [this sample project](https://github.com/Qolzam/react-social-ssr/blob/master/src/containers/other/OtherComponent.tsx) could help. Here I am using a [HOC wrapper](https://github.com/Qolzam/react-social-ssr/blob/master/src/util/withRedux.tsx). Let me know if any question.

**Comment by wiput1999** [comment]
@Qolzam I'm looking for some like boilerplate that comes with Razzle + After.js + Redux

**Comment by rayandrews** [comment]
@wiput1999, this boilerplate is works for me : https://github.com/natanelia/razzle-afterjs-redux-rnw-example

**Comment by wiput1999** [comment]
@rayandrews I’ve looked into this repository but I don’t want to add native into it

**Comment by singlepageprogrammer** [comment]
https://github.com/singlepageprogrammer/after.js-react-redux-ssr/tree/master/src 
i think that's not bad for reading

**Comment by nimaa77** [comment]
Hello everyone, 
there is a good example `with-redux` available in the examples folder.

1) HMR Ready
2) Store Rehydration 
3) access store object in `getInitialProps` (on server-side and client-side)
