### ISSUE TITLE
Connect with Redux

### ISSUE THREAD

**Issue by Qolzam** [jaredpalmer/after.js#135]
## Bug, Feature, or Question?
I'm trying to warp component with `react-redux` Provider component following below code.:
``` js
export default (...args: any[]) => (Component: any) => {
  
  const ConnectedComponent = connect.apply(null, args)(Component)

  class WithProviderComponent extends React.Component<any, any> {
    static async getInitialProps(data: any) {
      return { store: data.store }
    }
    constructor(props: any, context: any) {
      super(props, context)
    }
    
    render() {
      const { store} = this.props
  
      return (
        <Provider store={store}>
          <ConnectedComponent />
        </Provider>
      )
    }
  
  }

  return WithProviderComponent
}
``` 
And I pass store from server following code: 
``` js
...
server
  .disable('x-powered-by')
  .use(express.static(process.env.RAZZLE_PUBLIC_DIR!))
  .get('/*', async (req, res) => {
    try {
      const html = await render({
        req,
        res,
        routes,
        assets,
        // Anything else you add here will be made available
        // within getInitialProps(ctx)
        // e.g a redux store...
        store: sotre,
      })
      res.send(html)
    } catch (error) {
      console.error(error)
      res.json(error)
    }
  })
...
```
Everything work well except I get json parse error from After JS.

## Current Behavior
When I wrap component with provider I get bellow error:

``` js
Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 22
    at JSON.parse (<anonymous>)
    at ensureReady.js:57
```
refer to bellow line:
``` js
data = JSON.parse(document.getElementById('server-app-state').textContent);
```

## Desired Behavior
No error from after JS.

## Suggested Solutions
I have struggled many days but no idea!

---

- After.js Version: 1.3.1
- Razzle Version: 2.0.0-alpha.12
- React Version: 16.3.2
- TypeScript Version: 2.8.3
- OS: Mac
- Node Version: 8.9.4
- Package Manager and Version: yarn v1.5.1
- Demo Repo or Link: -

**Comment by Qolzam** [comment]
I have just recognized that in `getInitialProps(data: any)` when I return `{ store: data.store }` AfterJs trying to parse to Json object but it includes functions so it can happen. So I only can pass json valid object to props from `getInitialProps` function ?!

**Comment by Qolzam** [comment]
Seems I mis understood the concept of passing data with `getInitialProps`. It convert data to JSON to pass it to client job. Sorry for that.

**Comment by singlepageprogrammer** [comment]
https://github.com/singlepageprogrammer/after.js-react-redux-ssr/tree/master/src
i think that's not bad for reading
