### ISSUE TITLE
Question: getInitialProps() in child components

### ISSUE THREAD

**Issue by AndyArcherKG** [jaredpalmer/after.js#136]
Question

- Current Behaviour
Only parent can use `getInitialProps` the function is not called in any child components.

- Desired Behaviour
call getInitialProps to be called in a child component

Just wondered what the reasoning behind this was. 

---

- After.js Version: latest
- Razzle Version: 0.8.14
- React Version: 16.3.2
- TypeScript Version: N/A
- OS: OSX
- Node Version: 8.9.1
- Package Manager and Version: npm
- Demo Repo or Link: N/A

**Comment by AndyArcherKG** [comment]
It was more to keep the the application consise, e.g. an ajax call for content, an ajax call for header etc.
but i guess thinking about it - yeah this can just be done at the top level. 
It was more understanding the reasoning behind only allowing it at the parent.

**Comment by jaredpalmer** [comment]
A lot of this is going to change in the next 8 months when/if SSR suspense drops. We could perhaps walk the tree and recursively look for getInitialProps. However, I would probably want to build some sort of way to tell the walker not to descend any farther.

**Comment by jaredpalmer** [comment]
@AndyArcherKG @Qolzam Uber Engineering is (not so secretly) working on a React SSR and Node API framework (based on Koa) that does something like this called @fusionjs https://fusionjs.github.io

**Comment by AndyArcherKG** [comment]
@jaredpalmer thanks for the info, will take a look.
