### ISSUE TITLE
Package not found on install

### ISSUE THREAD

**Issue by jforaker** [jaredpalmer/after.js#14]
Cool repo! Trying it out but getting this on install (inside the examples/basic directory)...

`
error An unexpected error occurred: "https://registry.yarnpkg.com/@jaredpalmer%2fafter: Not found".
`

Seems its not listed in npm also https://www.npmjs.com/~jaredpalmer

**Comment by jaredpalmer** [comment]
Fixed.

**Comment by jforaker** [comment]
11 minutes. Hot damn 🔥
