### ISSUE TITLE
renderToNodeStream compatible ?

### ISSUE THREAD

**Issue by romainquellec** [jaredpalmer/after.js#143]
## Question

Hi ! Is it possible and does it make sense to use razzle/after with renderToNodeStream ?
Thanks.

**Comment by kasbah** [comment]
Hey, I just looked into it a little bit and it looks like it doesn't support it. You _can_ have an async renderer that returns a Promise though. 

Adding the ability to use renderToNodeStream wouldn't be too hard though the main problem is the use of Helmet. See https://github.com/nfl/react-helmet/pull/355 and https://github.com/staylor/react-helmet-async.

**Comment by krazyjakee** [comment]
I think this is still relevant and important for TTFB

**Comment by jschroed91** [comment]
Looks like this is on the roadmap but in the "next" section: https://github.com/jaredpalmer/after.js/issues/281
