### ISSUE TITLE
Errors within getInitialProps are swallowed

### ISSUE THREAD

**Issue by kasbah** [jaredpalmer/after.js#150]
## Bug
:beetle: 

## Current Behavior

If you encounter an error within your getInitialProps function it is silently ignored. E.g. with the simple example if you add the following, nothing happens. 

```diff
--- a/Home.js
+++ b/Home.js
@@ -5,6 +5,7 @@ import { Link } from 'react-router-dom';
 
 class Home extends Component {
   static async getInitialProps({ req, res, match, history, location, ...ctx }) {
+    throw new Error('fail');
     return { whatever: 'stuff' };
   }
```

If an error does reach the `catch` in server.js in the example then `res.json(error)` always seems to result in an empty JSON object response. 

## Desired Behavior

Errors are not swallowed but left to be caught while calling `render`. The example code should log errors to console as well as responding with JSON that contains the error message and stack trace. 

## Suggested Solutions

Remove these catch calls: 

```diff
diff --git a/src/loadInitialProps.tsx b/src/loadInitialProps.tsx
index a1dd257..1f1774e 100644
--- a/src/loadInitialProps.tsx
+++ b/src/loadInitialProps.tsx
@@ -16,11 +16,9 @@ export async function loadInitialProps(
               .then(() =>
                 (route.component as any)
                   .getInitialProps({ match, ...ctx })
-                  .catch(() => {})
               )
           : (route.component as any)
               .getInitialProps({ match, ...ctx })
-              .catch(() => {})
       );
     }
     return match;
```

Update the example to log and respond with errors correctly:

```diff

diff --git a/examples/basic/src/server.js b/examples/basic/src/server.js
index 540ec54..72fe464 100644
--- a/examples/basic/src/server.js
+++ b/examples/basic/src/server.js
@@ -22,7 +22,8 @@ server
       });
       res.send(html);
     } catch (error) {
-      res.json(error);
+      console.error(error)
+      res.json({message: error.message, stack: error.stack});
     }
   });

```
## Additional Information

---

- After.js Version: master i.e. e713035 
- Node Version: 9.4

**Comment by jonjamz** [comment]
I was getting a cryptic JSON error in the browser console on page load and it was due to an error in getInitialProps. Took me a while to figure it out.

**Comment by mrmartineau** [comment]
I know this ticket is closed, but I thought it might be useful to someone... We use [Youch](https://github.com/poppinss/youch) to show a better error notice in our app:

this an exerpt from the `catch` area in our `server.ts`:

```ts
    } catch (error) {
      if (process.env.NODE_ENV === 'production') {
        console.log('ERROR ');
        console.log(error);
        res.send(
          "We're sorry this page didn't load. We're working to exchange it for a better one."
        );
      } else {
        const youch = new Youch(error, req);
        youch.toHTML().then(html => {
          res.writeHead(200, { 'content-type': 'text/html' });
          res.write(html);
          res.end();
        });
      }
    }
```
