### ISSUE TITLE
Custom args not being passed to getInitialProps

### ISSUE THREAD

**Issue by nolandg** [jaredpalmer/after.js#156]
## Bug, Feature, or Question?
Bug

## Current Behavior
In the Readme, it's stated that After's `render()` function will pass custom args to the `getInitialProps()` of the `document`. This is called `customThing: 'thing'` in the basic example. This seems not to happen. No custom args arrive, just the `req, res, assets` etc arrive.

## Desired Behavior
The `getInitialProps` static method of `document` should receive any additional args passed to `render`.

## Suggested Solutions
https://github.com/jaredpalmer/after.js/blob/532fbb077ac18e1594aa52d14f6f455c6c22b983/src/render.tsx#L78

I think this call fails to pass a spread of `...rest` that it captures earlier. Was below the intended function?

````js
const { html, ...docProps } = await Doc.getInitialProps({
    req,
    res,
    assets,
    renderPage,
    data,
    match: reactRouterMatch,
    ...rest,
  });
````

## Additional Information
I'm using a custom render function but I don't think that affects it since `getInitialProps` is called before the actual render.

Let me know if this is what you want to happen and I'll submit a PR. Or I'm just crazy and doing it wrong.

**Comment by AlexCSR** [comment]
I've ran into this problem too. I tested this on clean official example and there was the same problem. Additional arguments are passed on server-side but not on client-side. The only prop I see on client-side is `staticContext: undefined` which is probably added by StaticRouter since one of its latest release.

**Comment by AlexCSR** [comment]
@nolandg a getInitialProps function works well on first load but still doesn't get any custom args when route changed to the component. Did you notice this problem? Any suggestions?

**Comment by Lizhooh** [comment]
No additional parameter injections were found in the latest version of npm (v1.3.1)

![image](https://user-images.githubusercontent.com/19299088/54874868-c1e54100-4e2e-11e9-90d9-73643b53e599.png)

**Comment by nolandg** [comment]
I think it's been a while since he's published.
