### ISSUE TITLE
Window scrolls to top before `getInitialProps` finishes

### ISSUE THREAD

**Issue by gkaemmer** [jaredpalmer/after.js#158]
## Bug, Feature, or Question?
Bug

## Current Behavior
If I navigate in the browser, the route transition is delayed until `getInitialProps` finishes, but `After.jsx` calls `window.scroll(0, 0)` immediately. So if you're at the bottom of the page when you click a link, you get momentarily scrolled to the top of the same page before the transition actually happens.

## Desired Behavior
Window should scroll to the top when the route transition completes, i.e. when `getInitialProps` resolves.

## Suggested Solutions
Move line 20 of `After.jsx` (`window.scroll(0, 0)`) into the handler on line 32, so that it gets called when `getInitialProps` resolves.

---

- After.js Version: latest
- Razzle Version: N/A
- React Version: 16
- TypeScript Version: N/A
- OS: N/A
- Node Version: N/A
- Package Manager and Version: N/A
- Demo Repo or Link: can provide if needed

**Comment by nimaa77** [comment]
fixed in #251
