### ISSUE TITLE
Browser's memory keeps increasing

### ISSUE THREAD

**Issue by jaabiri** [jaredpalmer/after.js#161]
## Bug, Feature, or Question?

Bug

## Current Behavior

I'm writing SSR APP by using after.js 
Recently I observed my app become slower and slower when running on 
browser after every click I made on ReactRouter.Link. I've opened Google Chrome Debugger for investigation,
then I see usage memory and DOM nodes  keep increasing after every click.

## Suggested Solutions

---

- After.js Version: latest
- Razzle Version:^0.8.14
- React Version:16
- TypeScript Version:N/A
- OS: N/A
- Node Version:N/A
- Package Manager and Version:N/A
- Demo Repo or Link:

**Comment by jaredpalmer** [comment]
Interesting, we haven't experienced that. What makes you think it's After.js?

**Comment by jaabiri** [comment]
Hey @jaredpalmer  thanks for your  response :) 

demo link : https://drive.google.com/file/d/18kTcqjl1ADWxVWgb0j75q64qsnr-L9sd/view?usp=sharing

repos example: https://github.com/jaabiri/ssrExample/tree/master/afterWithApollo
