### ISSUE TITLE
getInitialProps signature got change by pull #162

### ISSUE THREAD

**Issue by stepanh** [jaredpalmer/after.js#165]
## Bug
`ctx.match` has been renamed to `ctx.matched` - this seems to be unintentional and breaks existing code. This has been changed on `master` branch only (not released).
See https://github.com/jaredpalmer/after.js/blame/e3f1526c875dfa8597ee337feebc7765489af1bf/src/loadInitialProps.tsx#L13

## Current Behavior
`ctx.match` contains path and param info

## Desired Behavior
Keep current behaviour as in After 1.3.1

## Suggested Solutions
Rename vars in `loadInitialProps`. I'd be happy to do a PR.

---

- After.js Version: master @ e3f1526c875dfa8597ee337feebc7765489af1bf
- Razzle Version: irrelevant
- React Version: irrelevant
- TypeScript Version: irrelevant
- OS: irrelevant
- Node Version: irrelevant
- Package Manager and Version: irrelevant

**Comment by stepanh** [comment]
@dagda1 could you please clarify as this is your code?

**Comment by jaredpalmer** [comment]
Yeah that’s a mistake please fix

**Comment by stepanh** [comment]
As @dagda1 doesn't seem to be around, here is a fix by me: https://github.com/jaredpalmer/after.js/pull/174

**Comment by dagda1** [comment]
@jaredpalmer I changed it to `matched` because it was shadowing the outer `match`, it makes more sense now you have renamed it to `matchedComponent` but was there an actual bug here?  I thought I just renamed the var.  I can't see the bug

Unit tests are really the answer to this type of break

**Comment by stepanh** [comment]
@dagda1 yes, there was a bug - in `getInitialProps` I was getting `ctx.matched` instead of the expected `ctx.match`. Unit tests would be great, agreed :-)

**Comment by dagda1** [comment]
@stepanh apologies and I'll have a go at creating some unit tests.
