### ISSUE TITLE
How to use After.js?

### ISSUE THREAD

**Issue by francisrod01** [jaredpalmer/after.js#182]
## Suggested Solutions
Needs more information like this:

- npm install ....
- `createApolloClient` file don't found
- Is it require to use `razzle` or not? If `not`, how to implement without Razzle?

- After.js Version: 1.3.1
- Razzle Version:
- React Version: 16.5.2
- TypeScript Version:
- OS: Linux debian 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux
- Node Version: v.8.11.2
- Package Manager and Version: npm 6.4.1
- Demo Repo or Link:

# Bug

```
> nodemon src/server.js --exec babel-node --presets env,stage-2

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/server.js --presets env,stage-2`
module.js:549
    throw err;
    ^

Error: Cannot find module 'graphql/language/printer'
```

**Comment by krazyjakee** [comment]
Please say how you initiated your project with afterjs.

Was it by following this guide? https://github.com/jaredpalmer/after.js#razzle-quickstart

> nodemon src/server.js --exec babel-node --presets env,stage-2

This command doesn't seem to have anything to do with afterjs or razzle.
