### ISSUE TITLE
with-typescript example?

### ISSUE THREAD

**Issue by sdebaun** [jaredpalmer/after.js#190]
## Bug, Feature, or Question?

Is there an example of using this with typescript?

## Additional Information

---

- After.js Version:
- Razzle Version:
- React Version:
- TypeScript Version:
- OS: 
- Node Version:
- Package Manager and Version:
- Demo Repo or Link:

**Comment by tejovanthn** [comment]
Hey @jaredpalmer, is there a typescript version of the Document.js, or some guide to get something rolling there?
