### ISSUE TITLE
Refetch?

### ISSUE THREAD

**Issue by MarkPolivchuk** [jaredpalmer/after.js#193]
## Bug, Feature, or Question?

Is `refetch: (ctx?) => void` as defined in the [README](https://github.com/jaredpalmer/after.js#injected-page-props) implemented? 

It is undefined when I try to reference it from my SSR rendered component and I can't any references to it in the source.

## Current Behavior
```
class Sample extends React.Component {
    static async getInitialProps({ req, res, match }) {
      const data = await api.get('/my-api');
      return { data };
    }

    render() {
      const { data, refetch, prefetch } = this.props;
      console.log(prefetch); // THIS IS A FUNCTION
      console.log(refetch); // THIS IS UNDEFINED
      return (
        <div>Hello world</div>
      );
    }
  };
```

## Desired Behavior

For `refetch()` to be defined.

- After.js Version: 1.3.1
- Razzle Version: 2.4.0
- React Version: 16.7-alpha

**Comment by mrmartineau** [comment]
@MarkPolivchuk there is no mention of `refetch` aside from the README. @jaredpalmer is the readme out of date?
