### ISSUE TITLE
extending .babelrc

### ISSUE THREAD

**Issue by andrefox333** [jaredpalmer/after.js#194]
Question - If I am adding a plugin to the .babelrc file, do I need to add any existing plugins that after.js use to my new .babelrc file?

**Comment by aarohmankad** [comment]
I'd also like to know this! I'm using styled-components in my application, and want to use the [styled-components babel plugin](https://github.com/styled-components/babel-plugin-styled-components) to make `styled-components` play nicely with SSR.

Any other examples of after.js with styled-components would be helpful as well!

**Comment by simonmares** [comment]
This is domain of razzle https://github.com/jaredpalmer/razzle#customizing-babel-config, check https://github.com/jaredpalmer/razzle/tree/master/examples
