### ISSUE TITLE
After.js with Koa: res.status is not a function

### ISSUE THREAD

**Issue by ValeriaVG** [jaredpalmer/after.js#205]
## Bug, Feature, or Question?
Bug

## Current Behavior
Server throws an error `res.status is not a function` on every request with a dynamic part

## Desired Behavior
Should not throw an error

## Suggested Solutions
While Express has res.status function Koa.js has res.statusCode, but it should not be used as a setter. As a workaround existence and type check for res.status should be enough:
```js
if(res.status && typeof res.status === 'function') res.status(404)
```

A following code can be used inside server.js before render to set the status:
```js
ctx.res.status = status => {
      ctx.status = status
}
```
where `ctx` is koa context.

## Additional Information

---
- After.js Version: 1.3.1
- Razzle Version: 2.4.0
- React Version: 16.7.0
- TypeScript Version: -
- OS: MacOS 10.14.2
- Node Version: 9.11.2
- Package Manager and Version: yarn 1.13.0
- Demo Repo or Link: -

**Comment by krazyjakee** [comment]
@ValeriaVG can you try the solution here? https://stackoverflow.com/questions/44038958/koas-ctx-status-not-getting-sent-to-client

**Comment by ValeriaVG** [comment]
@krazyjakee that's not exactly what my issue was. The status code is sent correctly, koa takes care of it. But I did need to monkey-patch in order to get rid of the error.

**Comment by krazyjakee** [comment]
@ValeriaVG my apologies. I have the exact set up you are expecting with passing res to the context and setting status in getInitialProps `res.status(404)` and it is working. That's what lead me to believe there is some magic Koa is doing to change this.
