### ISSUE TITLE
--example with-afterjs project does not start due to webpack error

### ISSUE THREAD

**Issue by newbreedofgeek** [jaredpalmer/after.js#206]
## Bug, Feature, or Question?
Possible Bug

## Current Behavior
When I create a app via `create-razzle-app --example with-afterjs poca` and run `npm start` it breaks as there seems to be a webpack error.

## Desired Behavior
Running npm start should build the dev server and launch it

## Suggested Solutions
There seems to be some configuration issue with webpack or I am using a version of webpack / react etc that is not supported.

## Additional Information
```
 WAIT  Compiling...


✔ success client compiled in 10s 226ms

Compiling

● client

● server █████████████████████████ compiling (0%)  
 

✖ ｢wdm｣: Hash: deb1b5ac86099023d9ff
Version: webpack 4.29.0
Time: 10236ms
Built at: 01/30/2019 3:28:59 PM
                  Asset      Size  Chunks             Chunk Names
    static/js/bundle.js  1.89 MiB  client  [emitted]  client
static/js/bundle.js.map  2.06 MiB  client  [emitted]  client
Entrypoint client = static/js/bundle.js static/js/bundle.js.map
[0] multi ./node_modules/razzle/config/polyfills.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./src/client 52 bytes {client} [built]
[./node_modules/@jaredpalmer/after/build/index.js] 417 bytes {client} [built]
[./node_modules/object-assign/index.js] 2.06 KiB {client} [built]
[./node_modules/process/browser.js] 5.29 KiB {client} [built]
[./node_modules/promise/lib/es6-extensions.js] 2.6 KiB {client} [built]
[./node_modules/promise/lib/rejection-tracking.js] 2.81 KiB {client} [built]
[./node_modules/razzle-dev-utils/node_modules/react-dev-utils/formatWebpackMessages.js] 4.27 KiB {client} [built]
[./node_modules/razzle-dev-utils/node_modules/react-dev-utils/launchEditorEndpoint.js] 330 bytes {client} [built]
[./node_modules/razzle-dev-utils/node_modules/react-error-overlay/lib/index.js] 318 KiB {client} [built]
[./node_modules/razzle-dev-utils/webpackHotDevClient.js] 7.56 KiB {client} [built]
[./node_modules/razzle/config/polyfills.js] 1.06 KiB {client} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {client} [built]
[./node_modules/react-router-dom/es/index.js] 1010 bytes {client} [built]
[./node_modules/react/index.js] 190 bytes {client} [built]
[./src/client.js] 707 bytes {client} [built]
    + 159 hidden modules

ERROR in ./src/routes.js 11:13
Module parse failed: Unexpected token (11:13)
✔ success server compiled in 322ms

/Users/mark.paul/poca/build/server.js:978
throw new Error("Module parse failed: Unexpected token (11:13)\nYou may need an appropriate loader to handle this file type.\n|   component: asyncComponent({\n|     loader: function loader() {\n>       return import('./Home');\n|     }, // required\n|     Placeholder: function Placeholder() {");
      ^

Module parse failed: Unexpected token (11:13)
You may need an appropriate loader to handle this file type.
|   component: asyncComponent({
|     loader: function loader() {
>       return import('./Home');
|     }, // required
|     Placeholder: function Placeholder() {

  976 | /***/ (function(module, exports) {
  977 | 
> 978 | throw new Error("Module parse failed: Unexpected token (11:13)\nYou may need an appropriate loader to handle this file type.\n|   component: asyncComponent({\n|     loader: function loader() {\n>       return import('./Home');\n|     }, // required\n|     Placeholder: function Placeholder() {");
  979 | 
  980 | /***/ }),
  981 | 

    at Object../src/routes.js (/Users/mark.paul/poca/build/server.js:978:7)
    at __webpack_require__ (/Users/mark.paul/poca/webpack/bootstrap:682:1)
    at fn (/Users/mark.paul/poca/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/server.js (/Users/mark.paul/poca/build/server.js:999:65)
    at __webpack_require__ (/Users/mark.paul/poca/build/webpack:/webpack/bootstrap:682:1)
    at fn (/Users/mark.paul/poca/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/index.js (/Users/mark.paul/poca/build/webpack:/src/index.js:3:1)
    at __webpack_require__ (/Users/mark.paul/poca/build/webpack:/webpack/bootstrap:682:1)
    at fn (/Users/mark.paul/poca/build/webpack:/webpack/bootstrap:59:1)
    at Object.0 (/Users/mark.paul/poca/build/server.js:1072:18)


```

---

- After.js Version: latest
- Razzle Version: 2.4.1
- React Version: 16.2.0
- TypeScript Version:
- OS:  OSX
- Node Version: v10.15.1
- Package Manager and Version: 6.4.1
- Demo Repo or Link:

**Comment by nicklasfrahm** [comment]
@newbreedofgeek I can verify this. I do however not have a fix for this.

**Comment by xenu256** [comment]
Trying to install from scratch on Wndows 10, all latest versions, just runs "downloading" forever. without doing anything

**Comment by sh4hids** [comment]
I am also facing the same problem with the new razzle update. Does anyone have any solution yet?

**Comment by rs-saunders** [comment]
I can confirm this is also an issue for me too. @newbreedofgeek it does indeed look like a webpack config issue. Webpack is complaining that it doesn't understand the use of dynamic [import()](https://webpack.js.org/api/module-methods/#import-1)  which is used in the afterjs example for code splitting. 

You can work around this to at least get your app running again by using `require()` instead.  You'll need to wrap it in a promise if you are just swapping out lines.

Replace any imports e.g. `return import('./Home')` with `return Promise.resolve(require('./Home'))`

This got my app running again but I don't know the impact this will have on code splitting or performance. I think a real fix is required to the webpack config to understand dynamic imports again

**Comment by AibiTi** [comment]
Any fixes?

**Comment by davesteinberg** [comment]
Broken out of the box for a month and a half? The ideas behind this project are really interesting, but this is not a good sign.

**Comment by sh4hids** [comment]
@AibiTi see this:

> I can confirm this is also an issue for me too. @newbreedofgeek it does indeed look like a webpack config issue. Webpack is complaining that it doesn't understand the use of dynamic [import()](https://webpack.js.org/api/module-methods/#import-1) which is used in the afterjs example for code splitting.
> 
> You can work around this to at least get your app running again by using `require()` instead. You'll need to wrap it in a promise if you are just swapping out lines.
> 
> Replace any imports e.g. `return import('./Home')` with `return Promise.resolve(require('./Home'))`
> 
> This got my app running again but I don't know the impact this will have on code splitting or performance. I think a real fix is required to the webpack config to understand dynamic imports again

**Comment by mariusk** [comment]
I think there's a webpack plugin that handles the dynamic import transparently, but since Razzle (which After.js is built upon) is still stuck on babel 6 (and not the more current version 7) that plugin doesn't seem to work. Since I'm not a webpack/babel expert, trying to update a dependency of After.js to a current version is just a bit too much work.

**Comment by davesteinberg** [comment]
It's an npm problem that breaks webpack starting in 4.29.0. Please see my comment on the Razzle issue: https://github.com/jaredpalmer/razzle/issues/904#issuecomment-472935739
