### ISSUE TITLE
Custom/Async Rendering example not working for me.

### ISSUE THREAD

**Issue by secretlifeof** [jaredpalmer/after.js#207]
I have a question how to use Apollo and also Redux with afterjs. But this question is primarily Apollo integration.

I installed the example using razzle & with-afterjs. 

It just renders "{}". Nothing more.

Desired result would be a rendered website.

I don't have any suggestions how to solve this. I have tried to add a Query to home.js without any change. The website renders normally when I use:

`const customRenderer = (node) => ({ html: ReactDOMServer.renderToString(node) })`

Server.js code:
```
const server = express();
server
  .disable('x-powered-by')
  .use(express.static(process.env.RAZZLE_PUBLIC_DIR))
  .get('/*', async (req, res) => {
    const customRenderer = node => {
      const client = new ApolloClient({
        ssrMode: true,
        link: createHttpLink({
          uri: "http://localhost:1337/graphql",
        }),
      });

      const App = <ApolloProvider client={client}>{node}</ApolloProvider>;
      return getDataFromTree(App).then(() => {
        const initialApolloState = client.extract();
        const html = renderToString(App);
        return { html, initialApolloState };
      });
    };

    try {
      const html = await render({
        req,
        res,
        routes,
        assets,
        customRenderer,
        customThing: 'thing',
      });
      res.send(html);
    } catch (error) {
      res.json(error);
    }
  });

export default server;
```

---

- After.js Version: latest
- Razzle Version: 2.4.1
- React Version: 16.2.0
- OS: Mac OS Mojave
- Node Version: v11.9.0
- Package Manager and Version: Yarn 1.13.0

**Comment by krazyjakee** [comment]
customRenderer needs you to return an object synchronously - it does not support async code.

You can see it's definition here: https://github.com/jaredpalmer/after.js/blob/2c03aaab286224511bed5b7807b96da8d246df47/src/render.tsx#L30

You are welcome to create a PR to add this functionality.

**Comment by quinnvaughn** [comment]
I am also getting this exact issue, and just saying it's not async doesn't help me.

**Comment by krazyjakee** [comment]
@quinnvaughn in what way does it not help you?

**Comment by quinnvaughn** [comment]
You didn't answer how to actually solve the issue. How do I take the incorrect example and fix it to get the ApolloProvider to correctly work? Basically.

**Comment by quinnvaughn** [comment]
Just even adding the line
`const App = <ApolloProvider client={client}>{node}</ApolloProvider>;`
turns it into returning just {}. I don't even have to render that. Doesn't work with the ApolloProvider from either react-apollo or @apollo/react-hooks.

**Comment by smkhalsa** [comment]
I think this needs to be reopened. 

Async Custom Rendering [is supported](https://github.com/jaredpalmer/after.js/blob/master/README.md#customasync-rendering), but the typescript type doesn't seem to be correct.
