### ISSUE TITLE
Apollo client in getInitialProps

### ISSUE THREAD

**Issue by EirikFA** [jaredpalmer/after.js#217]
## Current Behavior
No way to add custom context/properties to values received by `getInitialProps`.

## Desired Behavior
Access my Apollo Client from `getInitialProps` in my components.

## Suggested Solutions
Ability to add custom context (in `server.js/tsx`/`client.js/tsx`).

## Additional Information
`withApollo` works to receive the client when the component renders, but the only way to do it in `getInitialProps` was by setting the client as a property on `req` on the server. I can then check for this in the component (verify email, always requested directly on server) and use the Apollo client there.

---

- After.js Version: `1.3.1`
- Razzle Version: `3.0.0`
- React Version: `16.8.6`
- TypeScript Version: `3.4.5`
- OS: Windows 10
- Node Version: `11.0.0`
- Package Manager and Version: npm `6.4.1`
- Demo Repo or Link: Not necessary?

**Comment by nimaa77** [comment]
Hello @EirikFA, you can do it simply by passing your client to render() on server.js file.
```js
// ./src/server.js

const client = new ApolloClient({
  cache,
  link
});
const html = render({
  req,
  res,
  routes,
  assets,
  client
});
```
Also, on client.js pass your Apollo client to `<After />`.

```js
// ./src/client.js

// create new apollo client
...
<After routes={routes} data={data} client={client} />
...
```

Now you can use client in `getInitialProps`.

```js
static async getInitialProps({ client }) {
  const data = await client.query(WHATEVER);
}
```

**Comment by EirikFA** [comment]
@nimaa77 I see. Thanks a lot! Was not aware of this, though I should have noticed haha.
