### ISSUE TITLE
What is the proper component to wrap with a Context Provider?

### ISSUE THREAD

**Issue by vspedr** [jaredpalmer/after.js#221]
## Bug, Feature, or Question?
Question

## Current Behavior
I tried wrapping the BrowserRouter component with a Context Provider in an app bootstrapped with razzle and after.js and retrieving its value further down the component tree. However the context value when rendered by the server is always `undefined`, then after the app is rerendered by the browser it receives the desired value as expected.

## Desired Behavior
To have the context value defined in the first render by the server, because some of my components depend on it.

## Suggested Solutions
Include a working example with a Context Provider wrapping the After.js app where the context value can be obtained both from the server and the client. 

## Additional Information
I came up with a minimal reproduction of the issue in [this repo](https://github.com/vspedr/react-responsive-context-demo)

To be more specific, I need to provide a guess of the viewport's width based on the user-agent header via context, which will determine which components should be rendered at first. Without the context value from the server, though, I have to wait for a render call in the browser to get the actual value. As the context value is `undefined` in the server, some components don't show up at all on the initial page load.

---
- After.js Version: 1.3.1
- Razzle Version: 3.0.0
- React Version: 16.8.6
- TypeScript Version: N/A
- OS: Ubuntu 18
- Node Version: 11.13.0
- Package Manager and Version: yarn@1.15.2
- Demo Repo or Link: https://github.com/vspedr/react-responsive-context-demo

**Comment by nimaa77** [comment]
check #225

**Comment by Damilola99-web** [comment]
I'm also having the same problem
