### ISSUE TITLE
How to use getInitialProps in functional components

### ISSUE THREAD

**Issue by Kaeon** [jaredpalmer/after.js#222]
## Bug, Feature, or Question?
Question

## Current Behavior
I can't get getInitialProps to work in functional components, as suggested in nextJS documentation this would work with something like 
```
const Component = () => {
...
}

Component.getInitialProps = async ({ req, res, match, store, ...ctx }: any) => {
const setting = await fetch(apiUrl);
  return { setting };
};

export default Component;
```

## Desired Behavior
Since I only use these kind of components (using hooks) I would like to see getInitialProps working with these components as well. Is there any way to do this?

---

- After.js Version: 1.3.1
- Razzle Version: 3.0.0
- React Version: 16.8.6
- TypeScript Version: 3.5.1
- OS:  Windows 10
- Package Manager and Version: npm

**Comment by erkmene** [comment]
@Kaeon I'm seeing that this is working as intended. To give a simple example:

```js
const Comp = (props) => {
    return (
      <div className="Comp">
        <p>This is a static paragraph, the next line is async.</p>
        <p>{!!props && !!props.results && props.results.current_user_url}</p>
      </div>
    );
}

Comp.getInitialProps = async ({ req, res, match, history, location, ...ctx })  => {
  let results = await axios.get('https://api.github.com');
  return {
    results: results.data
  }
}
```

The output has the second async line when seen through the browser, as well as from `curl` output as server rendered; both when run with `npm run start` and `npm run start:prod`.

**Comment by Kaeon** [comment]
Thanks @erkmene for confirming this is possible. My mistake was that I tried this from a child component, apparently this works only for top-level component as far as I understand looking at examples from Nextjs.
