### ISSUE TITLE
getInitialProps behavior with prefetch

### ISSUE THREAD

**Issue by VojtechVidra** [jaredpalmer/after.js#228]
## Bug or Question?
When prefetching some page `getInitialProps` is executed twice.

## Current Behavior
When running prefetch on some route the `getInitialProps` is executed and data is stored in cache. But when entering prefetched page `getInitialProps` is executed again, which would not be a big deal but when data is returned from second execution, props of the page comes from the prefetched execution.

## Desired Behavior
I would assume that the props of the page would be updated when the second execution is done. Or that second execution would never run.

## Suggested Solutions
🤷‍♂️

---

- After.js Version: 1.3.1
- Razzle Version: 3.0.0
- React Version: 16.8.6
- TypeScript Version: 3.5.3
- OS: MacOS 10.14.5
- Node Version: 12.6.0
- Demo Repo or Link: https://github.com/VojtechVidra/razzle-afterjs-typescript-example

**Comment by DrecDroid** [comment]
I don't know if this is related but when I click a React-Router Link (after the first render) the current page gets called twice one without the passed props from getInitialProps and the second time with the props generated in the initial render(SSR).
I use this wrapper for the components passed to afterjs's router.

```
function wrapComponent(Component){
  function wrapper(props){
    return props.__render? <Component {...props} /> : null
  }
  
  wrapper.getInitialProps = async function(props){
    let initialProps = Component.getInitialProps? await Component.getInitialProps(props) : {}
    initialProps.__render = true
    return initialProps
  }
  return wrapper 
}
```
