### ISSUE TITLE
Load Assets Faster !

### ISSUE THREAD

**Issue by nimaa77** [jaredpalmer/after.js#232]
## Current Behavior
After.js only send the main CSS and js files from server then on browser at ensureReady method it tries to fetch javascript and CSS files for the current code spilled page. it's too slow (even Google PageSpeed Insights warns about it)

## Desired Behavior
Send all CSS and JS needed for the current route from the server.

## Suggested Solutions
I maid a little library that fixes this problem but I'm not sure about new routes config file, it's little complicated and it's bad for DX (or maybe it's not, let me know), I need some help about routes and [this](https://github.com/nimacsoft/afterjs-assets#call-ensureready-after-window-load), more information on [afterjs-assets](https://github.com/nimacsoft/afterjs-assets) repo, if you think it's ok i can write tests and make PR. 

you can install and use the package from npm registry till the day PR get merged.

---

- After.js Version: 1.3.1
- Razzle Version:  not sure 2.4.1 or 3.0.0
- React Version: 16.9.0
- TypeScript Version: 3.5
- OS: 
- Node Version:
- Package Manager and Version:
- Demo Repo or Link: [https://github.com/nimacsoft/afterjs-assets](https://github.com/nimacsoft/afterjs-assets)

**Comment by nimaa77** [comment]
@jaredpalmer what's your idea?
all of this become possible after reading this [comment](https://github.com/jaredpalmer/razzle/blob/master/packages/razzle/config/createConfig.js#L356).

**Comment by s123121** [comment]
Just wanna clarify, I am in the process of optimizing speed for my `after.js` app. When you talk about `ensureReady` make the app too slow, are you talking about TTFB? 
https://web.dev/time-to-first-byte/

**Comment by nimaa77** [comment]
@s123121 
short answer: no.
TTFB is about server-side (i mean`server.js` file) but `ensureready` get called on the browser and have nothing to do with TTFB.

in order to have a better TTFB you can use cache for HTTP requests in getInitalProps method or cache the server response with a package called `cacheable-response`.

read this too: [Rendering On The Web](https://developers.google.com/web/updates/2019/02/rendering-on-the-web)

this issue is not about code execution performance. it's about making js and CSS files downloaded faster to get executed later.

**Comment by nimaa77** [comment]
nobody helped and I learned many new things, check #237.

**Comment by nimaa77** [comment]
MERGED 🎈
