### ISSUE TITLE
Publish master to npm?

### ISSUE THREAD

**Issue by gobengo** [jaredpalmer/after.js#236]
@jaredpalmer Will you please consider publishing master branch to npm?

Especially because it includes this great functionality: https://github.com/jaredpalmer/after.js/pull/231

I tried to depend via git URL, but the prepare script fails after npm install on my project that uses typescript 3 (after.js uses ts 2). I believe if you build it and push to npm, this won't be a problem even in ts >= 3 projects.

**Comment by nimaa77** [comment]
@gobengo can you check #237, I need some feedback :)

**Comment by nimaa77** [comment]
just clone and build the code from the master branch, and copy all files from the build directory to your node_module directory.
it's path is `node_modules/@jaredpalmer/after/build`

**Comment by nimaa77** [comment]
[v1.4.0 just released](https://github.com/jaredpalmer/after.js/releases/tag/v1.4.0), we can close this issue now.
