### ISSUE TITLE
Cant return 404 from server. 

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#241]
Hello, 
first of all this is an awesome library! thank you for that : )
my issue is that I cent seems to return 404. 
this is my code like the documentation : 

`class Article extends React.Component {

    static async getInitialProps({ req, res, match }) {

            try{
                const json_data = await axios(process.env.rest_api_article_data.replace('##article_id##',match.params.article_id));
            }catch (error) {
                res.statusCode = 404;
                if (error.response.status === 404) return { statusCode: 404 }
                return { error }
            }....
`
I am getting error page , with status code 200 : 

![image](https://user-images.githubusercontent.com/6458359/66896022-c5bff700-effc-11e9-90df-a0182f8c153e.png)

can you please help me? 
thanks!

**Comment by nimaa77** [comment]
hi, check your browser dev tools, I think you have a CORS error.

**Comment by maorkavod** [comment]
I will check that out!

thanks!

**Comment by maorkavod** [comment]
it was a bug inside my code, thank you any way !
