### ISSUE TITLE
ERROR : {"name":"Invariant Violation"}

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#242]
How do i get more helpful error than this one : 
{"name":"Invariant Violation"}

i have one component that sometimes crash my app with this error - {"name":"Invariant Violation"}.
and i cent debug it and understande where is the problame. how i get the actual error? 

thanks!

**Comment by nimaa77** [comment]
hello @maorkavod 

please add `console.log(error)` to server.js file, like below
```js
try {
  const html = await render({
    req,
    res,
    routes,
    assets,
  })
  res.send(html)
} catch (error) {
  console.error({ error }) // <= right here
  res.json({ error })
}
```

and then you can check for errors in your console.
