### ISSUE TITLE
Redirect with 404 from getInitialProps

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#244]
Hello,
im trying to return 404 in case of not found data, the console log working im inside the axios catch error, and follow the documantation, by my page still loaded with no data for component instead of redirect to 404 page. 

`static async getInitialProps({req, res, match}) {

            const json_data = await axios(process.env.rest_api_category_data.replace('##category_id##', match.params.category_id), {
                userAgent : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
            }).catch(function (error) {
                console.log(error);
                return { statusCode: error.response.status, error : error }
            });
			
}`

**Comment by nimaa77** [comment]
hello @maorkavod 

@jaredpalmer has not published master to npm yet, so you are not able to use this feature.
can you please, call him on twitter? publishing master to npm should not take more than 1 minute.

**Comment by maorkavod** [comment]
thank you, 
I send him also an Email regarding this issue.

**Comment by nimaa77** [comment]
also check #236

**Comment by DeviousM** [comment]
I figured we'd have to wait a really long time for him to publish as he seems to be busy with other projects, so I've published it under my namespace for the time being and I'll remove it when he releases an update. 
If you want to use it, have fun: `npm i @deviousm/after.js --save-dev`

**Comment by nimaa77** [comment]
@DeviousM v1.4.0 just released yesterday

https://github.com/jaredpalmer/after.js/releases/tag/v1.4.0

it includes Dynamic 404 and Redirects and more awesome features

now we can close this issue.

**Comment by DeviousM** [comment]
Cool! I checked previously if it was released, but didn't see that 😛
BTW - great work on that Dynamic 404 and Redirects @nimaa77, I find it super useful in my current project!

**Comment by nimaa77** [comment]
@DeviousM tnx ❤️

Right now I'm thinking about new React Concurrent Mode and Suspense for SSR.
and check [React Conf 2019](https://youtu.be/JDDxR1a15Yo) it's started right now

**Comment by maorkavod** [comment]
Hello @DeviousM 
im getting 404 :-/

![image](https://user-images.githubusercontent.com/6458359/67623107-297ec700-f82a-11e9-8cd8-25c27b19060a.png)

**Comment by maorkavod** [comment]
Hello @DeviousM 
Im getting 404 on install :-/
![image](https://user-images.githubusercontent.com/6458359/67623117-621ea080-f82a-11e9-9045-f6e0f192a29c.png)
