### ISSUE TITLE
Bug: getInitialProps not working as expected on client side

### ISSUE THREAD

**Issue by nimaa77** [jaredpalmer/after.js#250]
## Bug

When a user moves from page `/a` to page `/b`, `<After />` calls `getInitialProps` method for that page. (as expected)

## Current Behavior

URL Change  -> `getInitialProps` get called -> matched component get renderd on screen -> `getInitialProps` resolved -> component gets re-renered and can acess `getInitialProps` data from it's props  

this is very bad and there are some problems:
1. very bad UX, this will cause page jank since matched component gets rendered on-screen without any data, and we have to show `<Spinner />` till `getInitialProps` resolved
2.  scroll to top happen after `getInitialProps` resolved, so the user will see nothing (or footer) for a while
3. if we use data from `getInitialProps` with hooks, we have to write very complicated code
```jsx
function PageB({ data }) 
  const [count, setCount] = React.useState(data)

  if (!data) return <Spinner />

  return <span>{count}</span>
}

PageB.getInitialProps = () => {
  return new Promise(reslove => setTimeout(() => reslove({ data: 1 }) , 3000))
}
```
`data` is undefined so count is undefined, and to fix it we have to write an effect like below:

```jsx
React.useEffect(() => {
  setCount(data)
}, [ data ])

```
![not-concurrent](https://user-images.githubusercontent.com/25016067/68108328-ba296700-fefc-11e9-819a-db76c8d2f92e.gif)

## Desired Behavior

URL Change  -> `getInitialProps` get called -> `<After />` wait's on current location until `getInitialProps` resolved -> render matched component with data from `getInitialProps`

:rocket:  **This is SUSPENSE but not suspense** :rocket: 
user can interact with prev page since the new page data is going to fetch.

When a user moves from page `/a` to page `/b`, URL changes but the user still sees `/a` page on the screen till `/b` page data get fetched. also with nprogress we can show a progress bar on the screen to tell users everything is under control. if we add a little delay (about 500, 600ms) to the progress bar then we can have a really fast site. ([read this blog post about loading state and UX](https://uxmovement.com/navigation/progress-bars-vs-spinners-when-to-use-which/))

![image](https://user-images.githubusercontent.com/25016067/68094379-19638900-feb5-11e9-8b69-a79c12c0043c.png)

![concurrent](https://user-images.githubusercontent.com/25016067/68108311-b09fff00-fefc-11e9-90fc-287feeb9f360.gif)

## Suggested Solutions
I maid a PR to fix this :see_no_evil: 
Check #251 

## Additional Information
Jared missed a point about react-router-dom documentation. 

as [react-router-dom said:](https://reacttraining.com/react-router/web/api/Route/location-object)

> If a `<Route>` element is wrapped in a `<Switch>` and matches the location passed to the `<Switch>` (or the current history location), then the location prop passed to `<Route>` will be overridden by the one used by the `<Switch>`

and this is part of `After` component logic: 
```jsx
<Switch>
  {routes.map((r, i) => (
    <Route
      key={`route--${i}`}
      path={r.path}
      exact={r.exact}
      location={previousLocation || location} // <- ignored because `<Route>` wrapped inside `<Switch>`
      render={(props) =>
        React.createElement(r.component, {
          ...initialData,
          history: props.history,
          location: previousLocation || location,
          match: props.match,
          prefetch: this.prefetch
        })
      }
    />
  ))}
</Switch>
```

fix:
```jsx
<Switch location={previousLocation || location}> {/* <- this will work */}
  {routes.map((r, i) => (
    <Route
      key={`route--${i}`}
      path={r.path}
      exact={r.exact}
      render={(props) =>
        React.createElement(r.component, {
          ...initialData,
          history: props.history,
          location: previousLocation || location,
          match: props.match,
          prefetch: this.prefetch
        })
      }
    />
  ))}
</Switch>
```

fixing it is not that much simple as I explained above, I will explain more when my PR is ready.

you can check my website with buggy implementation at [https://staging.antivirus.ir](https://staging.antivirus.ir) and fixed version at [https://antivirus.ir](https://antivirus.ir). move between links on a slow connection (use slow 3G from google chrome dev-tools Network tab), and prefer mobile devices to really get what I tried to express, and what we are fixing here.

---

After.js Version: 1.4.0
Razzle Version: 3.0.0
React Version: 16.10.0
TypeScript Version: 
OS: Gnu/Linux Fedora 31
Node Version: 12
Package Manager and Version: yarn v1.17.3

**Comment by maorkavod** [comment]
I wrapped all the logic like this and its work like charm. 
i case of non ssr page the props will be null so you can defind default values. 

` static async getInitialProps({req, res, match}) {

        if(!process.browser) {
            try {
                const json_data = await axios(process.env.rest_api_category_data.replace('##category_id##', match.params.category_id), {
                    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
                });
                var weather_forecast = {data : null};
                try {
                    weather_forecast = await axios(process.env.weather_forecast);
                    parseString(weather_forecast.data, function (err, result) {
                        weather_forecast = result;
                    });
                } catch (error) {
                    console.log(error);
                }

                return {
                    app_env : process.env.env,
                    category_id: match.params.category_id,
					json_data : json_data.data

                };
            } catch (error) {
                console.log(error);
                return {statusCode: 301, redirectTo: "/404"}
            }
        }

  }
  
  
  
    constructor(props) {
        super(props);
        this.getComponent = this.getComponent.bind(this);
        this.state = {
            app_env: this.props.app_env,
            site_name: this.props.site_name,
			json_data: this.props.json_data,
        };
    }`

**Comment by nimaa77** [comment]
@maorkavod I don't understand what you trying to express here, can you explain more?

**Comment by blakek** [comment]
Until this is merged, is there a way to know the difference between a prop returned from `getInitialProps` that pending vs. a prop that has already resolved but was `undefined`?

**Comment by nimaa77** [comment]
you can return an object from getIntitalProps 
```js
getInitialProps = async () => {
  const dataFromApi = await getData()
  return { data: { dataFromApi } }
}
```
so if you want to check if server returend undefined you can check if data prop is undefined

`if (props.data === undefined)` then state is pending
`if (props.data.dataFromApi === undefined)` then state is resoleved and server response is undefined

**Comment by nimaa77** [comment]
since #251 gets merged, this problem is fixed.

**Comment by atulmy** [comment]
This flow seems against the Single Page Application's desired flow. Not sure why was this implemented , or atleast this should have been optionally triggered on by a flag to <After />.

> very bad UX, this will cause page jank since matched component gets rendered on-screen without any data, and we have to show till getInitialProps resolved

No it is not. Once the initial page load is done via SSR, rest of the flow should be similar to a normal SPA, i.e. route between the pages and mount the component immediately, then fetch the data.

CC: @jaredpalmer

**Comment by atulmy** [comment]
@nimaa77 can you expose the old `<After />` component or provide a flag to switch?
