### ISSUE TITLE
Run production build with custome PORT

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#253]
Hello,

how can i pass to port number to the command : 
NODE_ENV=production node build/server.js ? 

i need to run this application on the same server with 4-5 process on different ports.
is it possible?

**Comment by psobhanlo** [comment]
//razzle config js

please put below code into razzle.config.js

`
module.exports = {
    plugins: ["manifest", "scss"],
    modify(defaultConfig, { target, {
        clearConsole: true,
        host: 'localhost',
        port: 3000
     }}) {
        const config = defaultConfig
        if (dev === false) {
            delete config.externals
        }
        return config
    }
}`

**Comment by nimaa77** [comment]
> //razzle config js
> 
> please put below code into razzle.config.js
> 
> ` module.exports = { plugins: ["manifest", "scss"], modify(defaultConfig, { target, { clearConsole: true, host: 'localhost', port: 3000 }}) { const config = defaultConfig if (dev === false) { delete config.externals } return config } }`

it's totally wrong way to do it

**Comment by nimaa77** [comment]
create .env file in the root of your project and set PORT inside that file:
```
PORT=3000
```
read more at [https://github.com/jaredpalmer/razzle#build-time-variables](https://github.com/jaredpalmer/razzle#build-time-variables)
