### ISSUE TITLE
Missing .env variables on production build

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#254]
## Bug, Feature, or Question?
Missing  .env variables on production build.

## Current Behavior
on yarn start (development env) this works fine, i get get all the .env rows. 
but when i make 
yarn build
NODE_ENV=production node build/server.js 

im getting an error that the variable are undefined.
my component : 

`class Category extends React.Component {

    static async getInitialProps({req, res, match}) {

        if(!process.browser) {
            try {
                const json_data = await axios(process.env.rest_api_category_data.replace('##category_id##', match.params.category_id), {
                    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
                });
			} catch (error) {
                console.log(error);
                return {statusCode: 301, redirectTo: "/404"}
            }
        }
	
	}
}`

but when i request the page from my production build im getting an error : 
![image](https://user-images.githubusercontent.com/6458359/68210306-e79a1180-ffdd-11e9-93d6-16ed0190ab7b.png)

what im doing wrong? :(

thanks!

**Comment by nimaa77** [comment]
hello @maorkavod, you have to add `RAZZLE_` prefix to your environment variables.

```js
// .env
RAZZLE_rest_api_category_data=Foo
```

and in your code use it like below:
```js
axios(process.env.RAZZLE_rest_api_category_data)
```

to read more about `env` variables [follow this link](https://github.com/jaredpalmer/razzle#adding-environment-variables-in-env).
