### ISSUE TITLE
getInitalProps not getting properties on client

### ISSUE THREAD

**Issue by Kaeon** [jaredpalmer/after.js#257]
## Bug, Feature, or Question?
Bug

## Current Behavior
After ugrading to 1.4.0 I had two issues. 

1) In server.tsx I get a typescript error when adding extra properties. The following code:
`const html = await render({
              assets,
              document: Document,
              req,
              res,
              routes,
              test
              // Anything else you add here will be made available within getInitialProps(ctx), e.g a redux store...
            } );`
gives an error Object literal may only specify known properties, and 'test' does not exist in type 'AfterRenderOptions<unknown>'. Workaround is to provide the properties 'as any'.

2) getInitialProps works as expected on the server. But when I get to a page by using a client route the extra properties aren't available.
`ProfilePage.getInitialProps = async ({ history, location, match, test, req, res, ...ctx }: any) => {
  console.log('test')
  return { test };
};`
In the above example I get a value for test on the server, but on the client (after routing) it gives an undefined, I only get the history, location & match properties.

## Desired Behavior
Being able again to use the extra properties in ctx on the client.

## Suggested Solutions
?

## Additional Information

---

- After.js Version: 1.4.0
- Razzle Version: 3.0.0
- React Version: 16.11
- TypeScript Version: 3.7.2

**Comment by nimaa77** [comment]
hello @Kaeon,
if you want to access variable `test` in `getInitialProps` on browser. you must pass that variable as a prop to `<After />`.

```jsx
// client.js

ensureReady(routes).then(data =>
  hydrate(
    <BrowserRouter>
      <After data={data} routes={routes} test="WOW" 👈 />  
    </BrowserRouter>,
    document.getElementById('root')
  )
);
```

**Comment by Kaeon** [comment]
Hi @nimaa77 , thanks for the quick response. I think before the 1.4.0 version I could just access 'test'. 

If I try to add it as prop to `<After />` Typescript gives me error  **Property 'test' does not exist on type 'IntrinsicAttributes & Pick<AfterpartyProps, "data" | "routes">'.** I do get the value in the client though.

What I want to actually set as data is a Redux store, which is defined with a withRedux() HOC and passed to **window[ReduxTypes.__REDUX_STORE__]**. This window value doesn't exist yet at the point where I could add it in client.ts

**Comment by nimaa77** [comment]
umm, I think something is wrong.
check browser dev-tools console there must be a rehydration error ...

if you want to use redux and do SSR, you must send redux state to the client and use it before rehydration starts.

```jsx
// server.js

app.get("/*", async (req, res) => {
    const store = createStore();

    const customRenderer = node => {
      const App = <Provider store={store}>{node}</Provider>;
      return {
        html: renderToString(App),
        serverState: store.getState()
      };
    };

    const html = await render({
      req,
      res,
      routes,
      assets,
      document: Document,
      customRenderer,
      store
    });
  // ... rest of code
}
```

```jsx
// Document.js
import serialize from "serialize-javascript";

class Document extends React.Component {
  static async getInitialProps({ assets, data, renderPage }) {
    const page = await renderPage();
    return { assets, data, ...page };
  }

  render() {
    const { helmet, assets, data, serverState } = this.props;
    // get attributes from React Helmet
    const htmlAttrs = helmet.htmlAttributes.toComponent();
    const bodyAttrs = helmet.bodyAttributes.toComponent();

    return (
      <html {...htmlAttrs}>
        <head>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta charSet="utf-8" />
          <title>Welcome to the Afterparty</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {helmet.title.toComponent()}
          {helmet.meta.toComponent()}
          {helmet.link.toComponent()}
          {assets.client.css && (
            <link rel="stylesheet" href={assets.client.css} />
          )}
        </head>
        <body {...bodyAttrs}>
          <AfterRoot />
          <AfterData data={data} />
          <script dangerouslySetInnerHTML={{__html: `window.INITIAL_STATE = ${serialize(serverState)}` }}></script>
          <script
            type="text/javascript"
            src={assets.client.js}
            defer
            crossOrigin="anonymous"
          />
        </body>
      </html>
    );
  }
}

export default Document;
```

```jsx
// client.js
const store = createStore(
  reducers,
  window.INITIAL_STATE,
);

ensureReady(routes).then(data =>
  hydrate(
    <Provider store={store}>
      <BrowserRouter>
        <After data={data} routes={routes} store={store} />
      </BrowserRouter>
    </Provider>,
    document.getElementById("root")
  )
);
```

Check #248 for more info

**Comment by nimaa77** [comment]
As a side note, passing `ctx` to `<After />` have nothing to do with v1.4.0.
you can simply test this by installing other version ...

**Comment by Kaeon** [comment]
@nimaa77 Thank you very much for this, the example was very clear and easy! I was working with an earlier example based on a withRedux wrapper for nextJs before, which was much more complicated. Everything working as expected now.
