### ISSUE TITLE
Is there a normal way to disable the auto-scroll-to-top on route change?

### ISSUE THREAD

**Issue by DeviousM** [jaredpalmer/after.js#258]
## Question
Is there a normal way to disable the auto-scroll-to-top on route change? I mean normal without having to fork the after.js?

## Current Behavior
Every route change triggers the `window.scrollTo(0,0)` and it can be pretty infuriating when you're creating a UI that's route dependent, but doesn't need the "scroll-to-top" thing.

## Desired Behavior
There's a way to just disable it with either .env variable or some setting.

## Suggested Solutions
Just a simple .env setting that can be set. `SCROLLTOTOP=false` could probably do it.

---

- After.js Version: 1.4.0
- Razzle Version: 3.0.0
- React Version: ^16.10.2

**Comment by maorkavod** [comment]
join to the same question.

**Comment by nimaa77** [comment]
hello, there is no normal way to disable auto-scroll. but we can have one 😎
what's your idea about passing a prop to `<After />` component?

### Idea 1
```js
// ./src/client.js

ensureReady(routes).then(data =>
  hydrate(
    <BrowserRouter>
      <After data={data} routes={routes} scrollToTop={false} />
    </BrowserRouter>,
    document.getElementById('root')
  )
);
```
and default value for `scrollToTop` is `ture` so there is no breaking changes 🎉 
you can do some kind of magic (with help of context api 🤓) to disable/enable `scrollToTop` on the fly.

```js
// ./src/client.js

ensureReady(routes).then(data =>
  hydrate(
    <BrowserRouter>
      <ScrollToTopProvider>   
        {(scrollToTop) => <After data={data} routes={routes} scrollToTop={scrollToTop} />}
      </ScrollToTopProvider>
    </BrowserRouter>,
    document.getElementById('root')
  )
);
```
and in your components just change value of context whenever you want to.
you can pass ScrollToTopProvider setState function to `<After />` so you can controll that value from `getInitialProps` and your components.

### Idea 2
you have a param in `getInitialProps` (a ref) and you mutate it:
```js
MyPage.getInitialProps = ({ scrollToTop }) => {
  scrollToTop.current = false; // or true
};
```
or you can return `scrollToTop` from `getInitialProps` and change that value in your components ...

I personally prefer the second Idea since it won't re-render our components when we change its value.

**Comment by nimaa77** [comment]
let me know your thoughts about this @maorkavod @DeviousM

**Comment by DeviousM** [comment]
@nimaa77, to be honest the first one seems the most reasonable because it allows you to disable the scrollToTop globally (and I'm almost sure that it's the simplest solution and also the one that's going to be the most popular), though it will indeed not be suitable if somebody is going to toggle it as it will cause a massive rerender. 

Also - to be honest I'm not sure if it wouldn't be a good idea to have it both ways. I mean to have one global toggle if someone is wishing to switch it off globally and then have one in getInitialProps, which will allow for more refined control (though it still would be per-main-route as getInitialProps is not called anywhere else I think).

**Comment by nimaa77** [comment]
what if we put a ref inside a context, so we can change its value without any re-renders?

**Comment by nimaa77** [comment]
also, we are going to add react-router-match to after.js, so each nested route might have different scroll strategy ...

**Comment by DeviousM** [comment]
What do you mean by "add react-router-match"? 
I think ref would indeed solve the issue of rerenders, because it'd only hold a reference instead of updating the value by state change and it'd still stop `window.scrollTo` execution.

**Comment by nimaa77** [comment]
oh sorry, I mean [react-router-config](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config). something like #208 

I will create a pull request for this later tonight

**Comment by nimaa77** [comment]
@DeviousM 
we can't use ref with custom prop name, name of the prop should be _ref_:
```js
const scrollToTop = React.createRef(false);
...
<After data={data} routes={routes} ref={scrollToTop} />
```
 We should go with the first Idea 

In React 17 we can pass any value to any component without any need to call React.forwardRef ...

**Comment by nimaa77** [comment]
check this, [https://github.com/jaredpalmer/after.js/tree/feature/auto-scroll#disable-auto-scroll-globally](https://github.com/jaredpalmer/after.js/tree/feature/auto-scroll#disable-auto-scroll-globally)

you can install after.js from this branch and test it in your app before we make a release.

**Comment by nimaa77** [comment]
@DeviousM I found a bug :)
I'm going to change how we are doing it
there is no need to pass that ref to `<After />` component, just specify it in the `render` method at `server.js` file

```js
const autoScroll = false; // default is true
const html = render({ req, res, assets, routes, autoScroll });
```
