### ISSUE TITLE
Use without SSR?

### ISSUE THREAD

**Issue by devinrhode2** [jaredpalmer/after.js#259]
## Question!

I am curious if it's sensible to use razzle+after.js without ssr. I like the architecture, and having the option of turning on ssr if needed, but not having it on by default.

**Comment by devinrhode2** [comment]
Our backend (laravel) currently just serves an index.html created with CRA (with craco to customize a few webpack things). I'm wondering if intead of using cra+craco, can we use razzle+after.js, and still create a simple build with an index.html file.

**Comment by nimaa77** [comment]
hello @devinrhode2 
you can't use razzle for client-side apps, but I think you can Re-export `<After />` into your project and use `getInitialProps` for data-fetching and ...
