### ISSUE TITLE
deprecated lifecycles

### ISSUE THREAD

**Issue by emekalites** [jaredpalmer/after.js#260]
Hi,
componentWillReceiveProps has been deprecated, it'll be nice if its changed to UNSAFE_componentWillReceiveProps or fixed using the current react lifecycles.

**Comment by nimaa77** [comment]
check #237, fixed in that PR

**Comment by emekalites** [comment]
I'm hoping it'll get merged soon, a lot of cool changes in that PR.

**Comment by nimaa77** [comment]
@emekalites v3 is out this problem is solved ...

**Comment by emekalites** [comment]
Thanks just checked it, good job man!
