### ISSUE TITLE
Handling Authenticated Routes with asyncComponents

### ISSUE THREAD

**Issue by davidfloegel** [jaredpalmer/after.js#261]
Hi, we have some private routes in our app. What we do at the moment is wrapping a higher-order component around the component:

```js
const routes = [
  {
    path: '/private',
    component: requireAuth(PrivateComponent)
  }
]
```

The HOC checks the auth status of the user and redirects if the user isn't logged in.

This approach works just fine but I'm wondering what the best approach would be to mark routes as private when using asyncComponents. One option I can see would be wrapping the `requireAuth` part around the actual implementation in the component file but that seems a bit hacky.

Would love to see how others solved this problem!

Thanks
David

**Comment by jwrlee88** [comment]
We've been taking a similar approach as you, and we've also been wondering the same thing as well.

Commenting to follow the thread.

**Comment by nimaa77** [comment]
I'm using the [Redirect](https://github.com/jaredpalmer/after.js#redirect) feature to handle authentication. whenever the backend server responded with 401 I'll redirect the user to the login page.

**Comment by davidfloegel** [comment]
Still looking for some input on this :)

**Comment by nimaa77** [comment]
@davidfloegel should we add some functionality for this in After.js? 

I think users can easily handle this in getInitialProps and with the help of [axios interceptors](https://github.com/axios/axios#interceptors).

```js
// routes.js 

const routes = 
[
  {
    path: "/public",
    component: Public
  },
  {
    path: "/private",
    component: Private
  },
  {
    path: "/login",
    component: Login
  },
]
```

```js
// Private.js

Private.getInitialProps = async () => {
  try {
    const { data } = axios.get("/data/from/backend")
    return { data }
  } catch(error) {
    return error
  }
}
```

```js
// client.js
// use this method also in server.js
// call this before `render()` and `ensureReady()`

function setupAxios() {
  axios.interceptors.response.use(
    (response) => response,
    (error) => {
      // if backend server returned 401
      // so there is an authentication problem 
      if (error.response.status === 401) {
        return Promise.reject({ redirectTo: "/login", statusCode: 302 })
      }
      return Promise.reject(error)
    }
  )
}

```
