### ISSUE TITLE
[BUG] Page not change when navigate on client

### ISSUE THREAD

**Issue by dwncy** [jaredpalmer/after.js#263]
## Bug, Feature, or Question?
Hi, try to run example folder. When navigate from /home to /about, the route change but the page is not change.

## Current Behavior
Route change to /about but the page still use `Home`

## Desired Behavior
Page should be use `About`

## Suggested Solutions
Seems var `currentLocation` in After.tsx causing the bug.
```
const { location: currentLocation } = this.props

.....
.then(({ data }) => {
  // currentLocation ≠ this.props.location inside .then
  if (currentLocation !== nextProps.location) { 
       return  
  }
.....
```

## Additional Information

---

- After.js Version: MASTER Branch

**Comment by nimaa77** [comment]
I'm going to test it now ...

which version of after.js you are using ?

**Comment by dwncy** [comment]
master branch when try running https://github.com/jaredpalmer/after.js/tree/master/examples/basic

**Comment by nimaa77** [comment]
Thanks, I fixed.
I will go for a Pull Request in a minute.
