### ISSUE TITLE
Airbnb eslint error

### ISSUE THREAD

**Issue by lednhatkhanh** [jaredpalmer/after.js#27]
Right now I can't use airbnb eslint style because it's conflicting with the built-in eslint version, can we have an option to remove eslint entirely and install our own eslint version?

**Comment by jaredpalmer** [comment]
You should be able to just drop in your own .eslintrc?

**Comment by lednhatkhanh** [comment]
`eslint-config-airbnb` requires `eslint@^4.9.0` while after comes with `eslint@4.5.0` so when I try to install `eslint-config-airbnb` I get this warning:
![image](https://user-images.githubusercontent.com/9303093/34968859-5e3ba1a6-fa9e-11e7-9a0e-a6004e437d7e.png)
So please provide a method to remove the built-in eslint completely.

**Comment by BrunoScheufler** [comment]
I'd agree to either this solution or to upgrade after.js' ESLint entirely if this doesn't break anything

**Comment by kylealwyn** [comment]
I'd vote for not including ESLint as a dependency of after. Frameworks shouldn't impose dev dependencies. Maybe a better solution would be to publish an eslint-config to be extended from, if after really wants to provide stylistic boundaries

```
extends:
  - after
```

**Comment by jaredpalmer** [comment]
@kylealwyn I agree. Eslint should probably be removed.

**Comment by lednhatkhanh** [comment]
@jaredpalmer Please check #63 and let me know your opinion, thanks.

**Comment by lednhatkhanh** [comment]
Closed via #63

**Comment by jaredpalmer** [comment]
Will cut a release.
