### ISSUE TITLE
Refactor to be a Razzle plugin

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/after.js#28]
![yo-dawg-i-heard-you-like-toolkits-so-i-made-a-toolkit-for-your-toolkit-so-you-can-make-more-zero-con](https://user-images.githubusercontent.com/4060187/34967653-624a8256-fa32-11e7-8e6d-0f33d8413950.jpg)

**Comment by stoikerty** [comment]
This was my first thought upon seeing after.js...
Why isn't this just an extension on Razzle?
Is razzle more bloated than you initially thought?

Sorry to be such a critic Jared, I am a bit puzzled with After.js, it feels like fragmentation.

**Comment by jaredpalmer** [comment]
This could be. I would need to make changes to Razzle related to plugins. Wasn't sure anyone would care or like this, so the fastest thing was to just copy and modify what was necessary.

**Comment by stoikerty** [comment]
That makes sense :)
Looking forward to how this changes Razzle to be more flexible! I just realised razzle is still 0.x.x so you must be planning around perfecting the first major version 😊

**Comment by paOol** [comment]
ETA?

**Comment by jaredpalmer** [comment]
This weekend probs.
