### ISSUE TITLE
3rd-party scripts errors crush the application

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#287]
Hello,

First of all, thank you for the last npm update! 

I have a problem :
I load the script of the 3rd-party company that loads ads inside my application.
this 3rd-party company sometimes has js error like Uncaught TypeError...etc
this make my application show a blank white screen and that's it, my users are stuck with this. 
how can I make my application to ignore 3rd-party scripts errors? 

thank you very much!

**Comment by nimaa77** [comment]
use try/catch ?

**Comment by maorkavod** [comment]
@nimaa77 
Thank you for your reply.
the issue is that the code is not my code. this is a 3rd-party advertisers code that I load in my website companies such as Taboola & Outbrain, sometimes have exceptions that make my web app show blank screen.
