### ISSUE TITLE
Restore state not working after update to 1.5.0

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#288]
i have this code inside my componentDidMount : 

  this.setState(prevState => {
        prevState = JSON.parse(localStorage.getItem('category_temp_state'));
        return prevState;
      });

to restore the state after the user clicks back to return to my main app page.
this was working in version 1.4.0, but after the update, nothing happens. 
there is another way to restore the previews page state? 

thanks!

**Comment by nimaa77** [comment]
what happened to my answer :|

**Comment by nimaa77** [comment]
I wrote a long answer to your question last night ...

maybe this help you:
```js
const prevState = JSON.parse(localStorage.getItem('category_temp_state');
this.setState({ prevState });
```

but I personally prefer to handle this in `getInitialProps`:
```js
static getInitialProps({ req }) {
  if (!req) { /* only on browser */
    const prevState = JSON.parse(localStorage.getItem('category_temp_state'));
    return { prevState }
  }
}
```

**Comment by maorkavod** [comment]
@nimaa77 
Thank you, works like a charm! :)
