### ISSUE TITLE
page refresh error when getInitialProps fetch

### ISSUE THREAD

**Issue by qilovehua** [jaredpalmer/after.js#289]
my website: [https://qa.cunzj.com](url)
getInitialProps work well when using a Link to access the route.
but when I refresh the page, error happen and return "{}"
Any info appreciated, thanks! 
<img width="625" alt="error info" src="https://user-images.githubusercontent.com/12076175/74129034-92435100-4c19-11ea-8efe-6f7736234c65.png" />
<img width="625" alt="website step" src="https://user-images.githubusercontent.com/12076175/74129188-e817f900-4c19-11ea-9efb-9d136c7178e6.gif" />

**Comment by nimaa77** [comment]
hello, @qilovehua

open the server.js, file there must be a try/catch code block like this:
```js
try {
 const html = await render({
   req,
   res,
   routes,
 });
 res.send(html);
} catch (error) {
  res.json(error);
}
```
just replace `res.json(error);` with
```js
console.error(error);
res.json({ message: error.message, stack: error.stack });
```

and you can see the error message when you hit '/notes` page.

**Comment by qilovehua** [comment]
@nimaa77  Thank you very much!
