### ISSUE TITLE
Change redirectTo default statusCode from 301 to 302

### ISSUE THREAD

**Issue by DevAlien** [jaredpalmer/after.js#290]
## Bug, Feature, or Question?
Feature

## Current Behavior
redirectTo defaults to a 301 status code, which is Moved Permanently, which means that the browser everytime you try to go that URL will directly go to the next url, without even trying.

if you are not logged in and go to `/user/test` I will do a redirect to a login page and then after he logged in I redirect him back to `/user/test` but the browser knows that the page has Moved Permanently (301) and goes back to login or `/`

## Desired Behavior
I think in most of the cases people want to have 302, 301 is a very specific use case

## Suggested Solutions
Just changing the default status codes on redirects.

**Comment by nimaa77** [comment]
Hello, I think you have to use 401 or something else for authorization errors...
but yeah, that is my fault it must be 302 by default.

this is going to be breaking change, so I'm going to change this in the next MAJOR version
