### ISSUE TITLE
Routes not changing on history.push when called from componentDidUpdate

### ISSUE THREAD

**Issue by shtanaka** [jaredpalmer/after.js#302]
## Bug, Feature, or Question?
Routes are not changing on client side when history.push is called inside componentDidUpdate (or useEffect as well)

## Current Behavior
I am trying to perform a navigation when I get a prop changed from my redux state, but it stucks in a loop until reaches maximum update depth exceeded.

## Desired Behavior
Navigation happens with no issues.

## Suggested Solutions
I think it's somewhat related to [this issue from connected-react-router](https://github.com/supasate/connected-react-router/issues/159)

I downgraded to after v1.4.1 and it works well. No clues on what it might be for now.

## Additional Information
I noticed when I see the history object the `pathname` changes to the desired route, the `action` is properly set to 'REPLACE' but the actual page does not render. and the `key` property keep being generated until we overflow the update depth is exceeded.

code preview

```
class Login extends Component {
  componentDidUpdate() {
    const { error, history, isAuthenticated } = this.props;

    if (error) {
      toast(error);
    }

    if (isAuthenticated) {
      history.replace("");
    }
  }

  performLogin = (values, _actions) => {
    const { login } = this.props;
    login(values);
  };

  render() {
    return (
      <LoginStyled>
        <Header negative />
        <Section id="login-page">
          <div className="container-login">
            <div className="form-container-login">
              <LoginForm onSubmit={this.performLogin} />
            </div>
          </div>
        </Section>
      </LoginStyled>
    );
  }
}
```

relevant dependencies:
```
    "@jaredpalmer/after": "latest",
    "@rematch/core": "^1.0.6",
    "express": "^4.16.2",
    "formik": "^1.5.1",
    "razzle": "^3.0.0",
    "react": "^16.8.4",
    "react-dom": "^16.7.0",
    "react-helmet": "^5.2.0",
    "react-redux": "^6.0.0",
    "react-router-dom": "^5.1.2",
    "redux": "^4.0.1",
```

---

- After.js Version: 1.6.1
- Razzle Version: 3.0.0
- React Version: 16.8.4
- OS: Mac OS X 10.14.6
- Node Version: v8.11.3
- Package Manager and Version: yarn 1.19.1

**Comment by nimaa77** [comment]
hello @shtanaka,

can you please create an example repo for this?

also, update react and react-dom, react-redux to their lasted versions ...
