### ISSUE TITLE
Multiple Layouts

### ISSUE THREAD

**Issue by jwkellyiii** [jaredpalmer/after.js#303]
## Question
It seems After.js really makes it difficult to have multiple layouts in your application due to the way they want you to setup your routes. Setting up a single layout is easy, but multiple layouts is alluding me. Is this really the case? Or am I really just missing something?

Just wondering if someone has an example of something similar to below:

Some pages: use single column layout
Some pages: use two column layout
Other pages: use three column layout
default layout is single column

---

- After.js Version: 1.6.1
- Razzle Version: 3.0.0
- React Version: 16.13.1
- TypeScript Version:
- OS: OSX 10.15.3
- Node Version: 13.8.0
- Package Manager and Version: npm 6.13.6
- Demo Repo or Link: N/A

**Comment by nimaa77** [comment]
hello, @jwkellyiii
we are working on this with the help of `react-router-config` and nested routes you can apply any layout to your pages.

this how it looks like
```js
const routes = [
  {
    component: App,
    routes: [
      {
        path: '/',
        exact: true,
        component: asyncComponent({
          loader: () => import('./components/Home'),
          Placeholder,
        }),
      },
      {
        path: '/single-column-layout',
        exact: true,
        component: asyncComponent({
          loader: () => import('./components/single-column'),
          Placeholder,
        }),
       routes: [
        {
          path: "/single-column-layout",
          component: HeyIAmNestedInsideTheSingleColumnComponent
        },
      ]
      }
    ],
  },
];
```

and inside SingleColumn component:
```js
render() {
  return (
    <div>
      <div className="column-1">
         <AnyThingYouWant />
      </div>
        {this.props.renderNestedRoutes()}
    </div>
  )
}
```

**Comment by jwkellyiii** [comment]
Thanks for the info @nimaa77. 
I gave this a whirl, but it doesn't work right now. 

Then I reread your response.
You mention you are working on it. Any idea when this will work with After.js?

**Comment by nimaa77** [comment]
umm, implementing this is not that much hard.
I was a little busy, we are hitting the end of the month and the deadline ... 

the PR you should look for is #296 

V2 is going to be very much faster + nested routes

also, we are working on razzle to publish a new Minor version to fix some bugs and some new useful utilities
