### ISSUE TITLE
Using asyncComponent loads the component twice, on both the server and the client

### ISSUE THREAD

**Issue by kowsheek** [jaredpalmer/after.js#305]
Firstly, thank you @jaredpalmer for these amazing packages. You sir, are brilliant :) And thank you @nimaa77 for maintaining and doing amazing work as well 🙏 

## Bug, Feature, or Question?
Bug (or question if this is expected behaviour).

From my application and also the **basic** example, I found that using `asyncComponent` loads the component twice on the server then twice on the client. I am coming across this since I'm loading content into an iframe and am seeing flickering before the load of the iframe. The iframe seems to start loading them restart loading.

If the following is the expected behaviour, I'll have to investigate further where this comes from otherwise.

## Current Behavior
Doing this will output the log twice on the server, then twice on the client:
```
  {
    path: '/',
    exact: true,
    component: asyncComponent({
      loader: () => {
        console.trace('loading home')
        return import('./Home')
      }, // required
      Placeholder: () => <div>...LOADING...</div>, // this is optional, just returns null by default
    }),
  },
```
Trace on the client shows one load from:
```
loader | @ | routes.js:11
-- | -- | --
  | AsyncRouteComponent.load | @ | asyncComponent.js:54
  | AsyncRouteComponent.componentWillMount | @ | asyncComponent.js:67
```
And another from:
```
	loader	@	routes.js:11
AsyncRouteComponent.load	@	asyncComponent.js:54
```

Doing the following instead resolves the flicker I'm seeing but then the the components are not being code-split.

```
  {
    path: '/',
    exact: true,
    component: (props) => {
      console.log('loading home')
      return <Home {...props} />
    },
  },
```

## Desired Behavior

Using asyncComponent should load once on the server then hydrate on the client once.

## Suggested Solutions

May be the hydrate should be the only one to mount the components and not ensureReady? I'm not sure.

---

- After.js Version: 1.0.0
- Razzle Version: 3.0.0
- React Version: 16.3.2
- TypeScript Version: NA
- OS: MacOS
- Node Version: 10.17.0
- Package Manager and Version: 6.12.0
- Demo Repo or Link: https://github.com/jaredpalmer/after.js/tree/master/examples/basic

**Comment by nimaa77** [comment]
hello @kowsheek 

I'm not sure but I think, react mount components two times in development mode
can you try this in production mode (just run `yarn build` and then `yarn start:prod`)

**Comment by kowsheek** [comment]
Thanks for such a quick response @nimaa77. I will try it but I actually initially found this to be the case in production, you can try this for example: https://briovr.com/64f02db8-1c83-4f2e-899a-cb9069bc4901/emoji-hug

**Comment by nimaa77** [comment]
the problem is not about components that load two times.
you define getInitialProps inside the component, so we need that component to call getInitialProps of it.

```js
const match = matchPath(routes, pathname)
```
and this is content of the match object:
```js
{
  path: "/",
  exact: true,
  component: Home, // or maybe it's wrapped inside async component!
}
```
so we do something like this:
```js
const routeData = await match.component.getInitialProps({ res, req });
```

so this is why that `console.trace` called twice.

**Comment by nimaa77** [comment]
I think you have hydration problem and I think it's about redux
when you are in development mode do you have any hydration errors? you can find that error in your browser console (it's a development only error)

**Comment by kowsheek** [comment]
That could be a good call but no errors. I see warnings about componentWillMount depreciation.

**Comment by nimaa77** [comment]
strange

**Comment by nimaa77** [comment]
you are using after.js version 1 ?

**Comment by nimaa77** [comment]
update react and react-dom to the lasted version maybe this has something with react itself

**Comment by kowsheek** [comment]
I was listing the after.js version on the basic project. The versions on my project is after.js: 1.6.1. react: 16.13.0 and react-dom: 16.10.2. I'm able to reproduce this with the production build of the basic example as well.

I understood what you said about `getInitialProps` but this does not re-mount the component? From my tests only when I don't use `asyncComponent` do I get the expected behaviour.

I double checked and don't see any errors regarding hydration and this is my code for it:

```
const render = () => {
  ensureReady(RootRouter).then(data => {
    const preloadedState = fromJS(getSerializedData('preloaded_state'))
    const history = createBrowserHistory()
    const store = configureStore(preloadedState, history)

    hydrate(
      <Provider store={store}>
        <ConnectedRouter history={history}>
          <After data={data} routes={RootRouter} store={store} />
        </ConnectedRouter>
      </Provider>,
      document.getElementById('root')
    )
  })
}
```

**Comment by kowsheek** [comment]
I wonder if somehow the scripts for my app are being injected twice, I notice the bundle in the header and the footer. It's been quite the goose chase... I'm probably missing something simple :)

**Comment by nimaa77** [comment]
@kowsheek create a sample repo with minimal application logic and send me the repo link
