### ISSUE TITLE
Cannot read property 'Home' of undefined

### ISSUE THREAD

**Issue by Samuel-Celko** [jaredpalmer/after.js#309]
Hi there, first of all I'd like to thank you for creating/maintaining afterjs - it looks awesome. I've been having issues with SEO in my project made using CRA and decided to look for a simple SSR solution - afterjs seems just like the thing!

Right off the bat however, I'm having issues running the template project. Everything seems to compile fine but then upon entering a route (say "/") I get the following error

```TypeError: Cannot read property 'Home' of undefined at Object.getAssets```

Any idea what I'm doing wrong? I've made no changes to the initial template setup.

node v12.16.1

```
"@jaredpalmer/after": "^2.0.0-1",
"after": "^0.8.2",
```
Thanks in advance for any help!

**Comment by nimaa77** [comment]
hello @Samuel-Celko, it's my mistake :)

just run `yarn add @jaredpalmer/after@16.1`and it will start working

### why it's not working?
version 2 of After.js is ready and it works BUT it needs a little configuration in the wepback side, and as you may know, we are using Razzle for webpack config.

the new version of razzle is ready :)
https://github.com/jaredpalmer/razzle/pull/1178
the only problem is => IT'S NOT DEPLOYED ON NPM YET (I asked from @jaredpalmer to tag a new version on npm) 

#### Why We Released `after` version 2?
I didn't want to release version 2 under stable tag :)
this is why we added a prerelease version to it ^2.0.0-1 (that `-1` is a prerelease thing)
but IDK why npm is using that as stable tag :)

so when you run `yarn add @jaredpalmer/after` npm will install 2.0.0-1 ...

**Comment by Samuel-Celko** [comment]
@nimaa77 thanks for that, all working now!

I'll be keeping an eye out for that release :)

**Comment by anasbud** [comment]
When will Razzle be published ? I've been using after@2 and followed the upgrade guide. Everything went well until I got an error regarding Chunks plugin in Razzle...

**Comment by nimaa77** [comment]
did you install the new version of the razzle manually?
you have to clone razzle and check out the next branch and then link razzle to your project

**Comment by anasbud** [comment]
Yep, linking razzle project made the trick. Thank you.
