### ISSUE TITLE
Serving on custom path

### ISSUE THREAD

**Issue by meghprkh** [jaredpalmer/after.js#31]
How to serve the site in `start:prod` on a custom path, say `/new`?

**Comment by jaredpalmer** [comment]
I need to look at how CRA handles this. Probably some public path magic

**Comment by meghprkh** [comment]
Idk, about cra in production, but cra build handles the static URLs fine,
and its easy to handle the react router by changing route of the base
route. Also since this is an isomorphic app, Link too should handle it if a
relative URL is provided imo
