### ISSUE TITLE
Usage with razzle to create dynamic routing

### ISSUE THREAD

**Issue by Joelgullander** [jaredpalmer/after.js#311]
## Question

Basicly we will use razzle for server-rendering of a react application with set of static routes together with dynamic routes that will be resolved by server / CMS. 

Would after.js be a good complement to dynamically create the routing-list?

Which of the steps would be best?: 

* Fetch all routes by an api-call and build up a route-list with the response

* Fetch only the url and resolve which pagetype. 

The api call would return a json of such: 

`
{
  url: "/",
  name: "PageName",
  type: "StartPage"
}
`

Where I would want to create a route for / -> `<StartPage />`

How would you approach this problem?

**Comment by nimaa77** [comment]
hello @Joelgullander 

let me first explain after.js
after.js = react-router + getInitialProps + code splitting
for creating a universal web app we need webpack config that works in SSR, by default for all examples in this repo we are using razzle but YOU CAN USE ANY WEBPACK CONFIG THAT YOU WANT

so basically if you can do it with razzle you can also do it with after.js (and vice versa)

### how to solve this problem?

first: you have to create components and put them in your bundle (for better performance load them dynamically with dynamic import syntax)

then you have to create your routes dynamically!

this is a valid react-router route config

```js
[
  {
    path: "/",
    exact: true,
    component: () => import("./Home")
  }
]
```

you have an endpoint for getting routes from the backend and you will call it before you call the `render` function in server.js:

```js
const { data } = await axios.get("/api/dynamic-routes")
const routes = mapDynamicRoutesWithComponents(data)
render({ res, req, routes, assets })
```

you must implement `mapDynamicRoutesWithComponents` yourself but as a side note you have to pass the `routes` array to the client-side so it react could be able to rehydrate the app on client-side

you can use `< SerializeData />` on your custom Document.js file and `getSerializedData()` on the client.js file (check with-redux example for more info) to handle that

**Comment by Joelgullander** [comment]
Thanks for the clarification nimaa. I guess I got confused that afterjs was an alternative to razzle. 

I am attempting your suggestion above and following the example with redux, and added typescript. However it fails on:

`
    at Object.getAssets (/Users/joelgullander/xxx/xxx/xxx.Client/node_modules/@jaredpalmer/after/src/getAssets.ts:22:11)
    at /Users/joelgullander/xxxx/xxx/xxx.Client/node_modules/@jaredpalmer/after/src/render.tsx:121:31
    at step (/Users/joelgullander/dynamicdog/xxxx/xxxx.Client/node_modules/@jaredpalmer/after/build/cjs/render.js:40:23)
    at Object.next (/Users/joelgullander/xxxx/xxx/xxx.Client/node_modules/@jaredpalmer/after/build/cjs/render.js:21:53)
    at fulfilled (/Users/xxxx/xxxx/xxx/xxxx.Client/node_modules/@jaredpalmer/after/build/cjs/render.js:12:58)
 ERROR  all async routes must have a chunkName property with value of /* webpackChunkName: "MyChunkName" */ check your routes config or use babel-plugin-after
`

My routes looks like:

`
import React from 'react';
import { asyncComponent, AsyncRouteProps } from '@jaredpalmer/after';

const routes: AsyncRouteProps[] = [
  {
    component: asyncComponent({
        Placeholder: () => <div>...LOADING...</div>, // this is optional, just returns null by default
        loader: () => import('./common/containers/Home'), // required
    }),
    exact: true,
    path: '/',
  }
];

export default routes;
`

**Comment by nimaa77** [comment]
ok, this is my fault install `@jaredpalmer/after@1.6.1` and you are good to go

**Comment by Joelgullander** [comment]
Thanks buddy. Works like a charm. 

While I have you here.... Do you see any issues with conditionally lazyloading a file containing all the pages conditionally or will that break the chunking in general? Better explained, do I need to explicevely adding imports to the components, ex` import('../../common/pages/HomePage'`

Example: 

```
export const mapDynamicRoutesWithComponents = (routes: EpiserverRoute[]): AsyncRouteProps[] => {
    const mappedRoutes: AsyncRouteProps[] = routes.map((route) => {
        return {
            path: route.url,
            exact: true,
            component: asyncComponent({
                // TODO: Make sure this actually chunks all the different pages....
                loader: () => import('../../common/pages').then((module) => module.default[route.pageType]),
                Placeholder: () => <div>...LOADING...</div>, // this is optional, just returns null by default
            })
        };
    });

    return mappedRoutes;
};
```

The thing that i'm wondering about is: 
 `import('../../common/pages').then((module)` => module.default[route.pageType]),`

**Comment by nimaa77** [comment]
umm, I think asyncComponent only works with default exports

**Comment by nimaa77** [comment]
what about this?

```js
const Home = () => import("./Home")
const About = () => import("./About")
const Shop = () => import("./Shop")

function getComponentForPath(name) {
  switch(name) {
    case "Home":
     return Home;
    case "About":
     return About;
    case "Shop":
     return Shop;
  }
}

const mappedRoutes = routes.map((route) => {
    return {
        path: route.url,
        exact: true,
        component: asyncComponent({
            loader: getComponentForPath(route.pageType), 
        })
    };
}
```

**Comment by Joelgullander** [comment]
Looks good i'll try and compare. 

By the way: 

> you must implement mapDynamicRoutesWithComponents yourself but as a side note you have to pass the routes array to the client-side so it react could be able to rehydrate the app on client-side

Do you mean passing the transformed routes by `mapDynamicRoutesWithComponents ` or pass the api-data and transform them again in client-side?

**Comment by nimaa77** [comment]
you should transform them again on the client-side

**Comment by Joelgullander** [comment]
Thanks. Works like a charm. I'll post a PR to the examples sections later on in the week if someone else is looking for inspiration. Good night.
