### ISSUE TITLE
How to ensure that getInitialProps only runs on the server side?

### ISSUE THREAD

**Issue by sessionboy** [jaredpalmer/after.js#314]
## Question
I don't know why allow getInitialProps to run on both the client and server, but I expect it to run only on the server side, just as the [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) method of next.js does.

**Comment by nimaa77** [comment]
that's a feature that I always wanted to add to after.js 

it's easy to implement this, I'm going to work on in this weekend

**Comment by nimaa77** [comment]
ok, about two weeks ago I had a question about `getServerSideProps` in the technical details section of [next.js documentation](https://nextjs.org/docs/basic-features/data-fetching#technical-details-2) they said:
> When you request this page on client-side page transitions through next/link (documentation) or next/router (documentation), Next.js sends an API request to the server, which runs getServerSideProps. It’ll return JSON that contains the result of running getServerSideProps, and the JSON will be used to render the page. All this work will be handled automatically by Next.js, so you don’t need to do anything extra as long as you have getServerSideProps defined.

### How they request for data?
with fetch, Axios, xhr?
what if someone wants to add custom header to that request!!!

### How this works with SWR? 
take a look at this link https://github.com/zeit/swr#ssr-with-nextjs

```js
export async function getServerSideProps() {
  const data = await fetcher('/api/data')
  return { props: { data } }
}

function App (props) {
  const initialData = props.data
  const { data } = useSWR('/api/data', fetcher, { initialData })

  return <div>{data}</div>
}
```

next docs said: `next.js` will call that API endpoint automatically when the URL changes
so when we add SWR hook how they understand that next.js should not call that endpoint, since we added useSWR hook?

**Comment by nimaa77** [comment]
or maybe they traverse the AST and find useSWR function calls (this is crazy don't laugh at me)

I really want to know =)))))

**Comment by sessionboy** [comment]
Here,maybe you can look at the [source code](https://github.com/zeit/next.js/blob/canary/packages/next/next-server/server/render.tsx#L621) that calls this method.

**Comment by sessionboy** [comment]
Its flow seems to be this:  `client` --> request server's `html` -->  execute `getServerSideProps` method to get data -->  return `html + data`.

**Comment by nimaa77** [comment]
forget about `next.js`, let's talk about the flow in `after.js`:

`on the server`: for the first request (the initial request) we call `getServerSideProps` and that function call will return us the props for the `<Page />` ...

`on the client`: when the user navigates between the pages we don't do anything, the developer should write the logic for data fetching on client-side himself 

something like this:
```js
export async function getServerSideProps() {
  const data = await fetcher('/api/data')
  return { props: { data } }
}

function MyPage (props) {
  const initialData = props.data
  const { data } = useSWR('/api/data', fetcher, { initialData })

  return <div>{data}</div>
}
```

**Comment by nimaa77** [comment]
and also we should add a helper function that mounts `getServerSideProp` as an express handler:

```js
const app = express();

// or any other URL
app.get("/api/FOO", async (res, req) => {
  const data = await getServerSideProps({ res, req });
  res.json(data);
})
```

**Comment by sessionboy** [comment]
But this is no different from getInitialProps, and it is still called on server-side and client-side.
I want to put the logic of obtaining data on the server-side processing, and the client-side only handles the mutation (create, delete, update) logic.

**Comment by nimaa77** [comment]
> But this is no different from getInitialProps, and it is still called on server-side and client-side.
> I want to put the logic of obtaining data on the server-side processing, and the client-side only handles the mutation (create, delete, update) logic.

yes exactly, it's possible with what I said 

actually `getInitialProps` will get called on both server and on client
but `getServerSideProps` only called on the server-side, and you can call `getServerSideProps` yourself (with axios, react-query, swr, ...)

**Comment by sessionboy** [comment]
How to call? Like this ? : 
>```
> // or any other URL
> app.get("/api/FOO", async (res, req) => {
>   const data = await getServerSideProps({ res, req });
>   res.json(data);
> })
> ```
Do I need to do this for every route?

**Comment by nimaa77** [comment]
no, after.js will do that automatically
you just to call a function that you can import it from after.js ...

**Comment by sessionboy** [comment]
I see, this is great.

**Comment by sessionboy** [comment]
Will getServerSideProp be released with `react-router v6`? I look forward to this.

**Comment by nimaa77** [comment]
umm, not really 

it doesn't have anything with RR6

I will try to implement this now :)

**Comment by atulmy** [comment]
`getInitialProps` should be called on server and on client, it should be called asynchronously to the router. After upgrading `after.js`, whole website feels janky as when navigating between pages, the component is mounted only after `getInitialProps` is awaited which is a very bad UX.

**Comment by nimaa77** [comment]
@atulmy check #348
