### ISSUE TITLE
separation of after.js and react-router

### ISSUE THREAD

**Issue by sessionboy** [jaredpalmer/after.js#315]
## Feature
I am using [react-router v6](https://github.com/ReactTraining/react-router/releases), but since after.js does not support react-router v6, I cannot use it.

Maybe `after.js` and `react-router` should not be bundled together, that you can switch the version of react-router at any time.In addition, I can even try other routes.

**Comment by jaredpalmer** [comment]
Agree. We should probably support RR6 I guess

**Comment by nimaa77** [comment]
hello @sessionboy for sure we are going to add react-react v6 support

I will create a canary release with support for RR-v6

**Comment by sessionboy** [comment]
Thanks, I look forward to it.
