### ISSUE TITLE
accessing the store inside component using useSelector hook 

### ISSUE THREAD

**Issue by samuelcelko** [jaredpalmer/after.js#316]
Hi there, I'm trying to access the store inside a component - my setup is inspired by the "with-redux" example although using function components and typescript.

I'm wrapping the app inside `client.ts` like so

```     
<Provider store={store}>
        <After data={data} routes={routes} store={store} />
</Provider>
```

and also passing the store in the render function inside `server.ts`

However, when trying to access the store using the `useSelector` hook I get the following error: 
```
{"message":"could not find react-redux context value; please ensure the component is wrapped in a <Provider>"
```
I can see the store with its contents in react dev tools.

Does anyone know what I'm doing wrong?
Thanks a lot!

**Comment by nimaa77** [comment]
Hello, I think you forgot to render `<Provider />` on the server-side!

check this link
https://github.com/jaredpalmer/after.js/blob/master/examples/with-redux/src/Document.js#L16

**Comment by samuelcelko** [comment]
I did indeed, thanks for the quick resoponse!
