### ISSUE TITLE
How to fix  'renderStatic' of undefined

### ISSUE THREAD

**Issue by thinnakrit** [jaredpalmer/after.js#321]
I had this problem

`TypeError: Cannot read property 'renderStatic' of undefined`

`
at ~/node_modules/@jaredpalmer/after/src/render.tsx:129:20
    at step (~/node_modules/@jaredpalmer/after/build/cjs/render.js:40:23)
    at Object.next (~/node_modules/@jaredpalmer/after/build/cjs/render.js:21:53)
    at fulfilled (~/node_modules/@jaredpalmer/after/build/cjs/render.js:12:58)
`

Thank

| Software         | Version(s) |
| ---------------- | ---------- |
| React            |16.13.1|
| After.js         |1.6.1|
| Razzle           |3.0.0|
| Razzle Plugins   |
| TypeScript       |
| Node             |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by nimaa77** [comment]
hey I saw you closed the issue, but your problem is react-helmet

probably you are using v6 of react-helmet that was not compatible with after.js 1.6.1

I released after.js v3 today with the support of react-helmet v6
