### ISSUE TITLE
Provide examples with typescript

### ISSUE THREAD

**Issue by sessionboy** [jaredpalmer/after.js#322]
## 🚀 Feature request
I like typescript, but I don't see an official example with typescript.

**Comment by nimaa77** [comment]
sure, let's [merge this to razzle](https://github.com/jaredpalmer/razzle/pull/1275) and then we can easily add typescript to after.js

**Comment by marjorg** [comment]
@nimaa77 When you get around to adding TS examples, can you add one for using getInitialProps with functional components as well?

Like it's used here: https://github.com/jaredpalmer/after.js/issues/222
