### ISSUE TITLE
`match` in `getInitialProps` always points to `/` in client

### ISSUE THREAD

**Issue by suciudan** [jaredpalmer/after.js#324]
### Current Behavior

In client, when navigating from a page to another, the `ctx.match` from `getInitialProps` always matches `/`. 
On initial page load (server), `ctx.match` has the correct value.

### Expected behavior

Home (/) -> About (/about)

Client side:
Expected `ctx.match.path=/about`
Received `ctx.match.path=/`

Server side:
Expected `ctx.match.path=/about`
Received `ctx.match.path=/about`

### Reproducible example

Tested with `examples/basic/`. You can find the repo [here](https://github.com/suciudan/after.js-router).

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            | 16.13.1
| After.js         | 3.0.0
| Razzle           | 3.1.0
| Razzle Plugins   |
| TypeScript       |
| Node             | 13.13.0
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by nimaa77** [comment]
👀let me see

**Comment by nimaa77** [comment]
ok I found the problem 
fixing now

**Comment by nimaa77** [comment]
https://github.com/jaredpalmer/after.js/tree/v3.0.1

**Comment by suciudan** [comment]
Tested it on my end and it works. Thank you!

**Comment by nimaa77** [comment]
you're welcome
