### ISSUE TITLE
Question about route transitions

### ISSUE THREAD

**Issue by Joelgullander** [jaredpalmer/after.js#327]
## ❓Question

So I have one question if this is something that could be added into afterjs or is already possible with writing own logic. 

When a user visits the site I fetch the route for that url-slug that comes in. In this example `/about-us`.

With after.js this url has now been fetched by SSR and the dynamicly resolved routinginformation has been populated to the route-table that after.js consumes. 

```
[
  {
        path: "/about-us",
        exact: true,
        component: asyncComponent({
            loader: () => import('./AboutUs'),
            Placeholder: () => <div>...LOADING...</div>
        })
  }
]
```

Our routing-table now consists of one route for the `/about-us` url match. 

Now to my question... When a user clicks a link that has a path to another route for example `/news` I would like to lazily fetch the routing-information and populate the routing-table with this new data. And preferably intercept the routing so that the user can remain on the old page until the promise for the new route has been resolved or rejected. 

Basicly my use case is that if possible I would like to get around with not building the entire routingtable with thousands of routes before client is initialized and only append routes that user wants to navigate to.

I am sorry if this is outside of after.js scope and if the question is more of a general question due to not having staticly created routes.

**Comment by nimaa77** [comment]
hello 

I didn't get it

can explain more
