### ISSUE TITLE
create a main layout to share common parts

### ISSUE THREAD

**Issue by hamed1992** [jaredpalmer/after.js#332]
hi there
i'd like to create a main layout and share my common parts like Header , footer & Sidebar Components to it , and only change the certain part of my app like CRA.  
i couldn't find any solution for this situation.
is there any feature to do that?
or we have to repeat those common component in each page? 
thank u ...

**Comment by faizanathar** [comment]
This example will help you out https://github.com/jaredpalmer/after.js/tree/master/examples/layout-component

**Comment by hamed1992** [comment]
Wooow , thank u thank u thank u  ,It was very usefull .😊
