### ISSUE TITLE
Repo example with After.js

### ISSUE THREAD

**Issue by waynelinks** [jaredpalmer/after.js#334]
## ❓Question
Can anybody point me to a good repo thats been built with After.js, Have checked out the example section. Looking for a complete project eg. blog, something with api requests. Just want to see how other people approaches it

**Comment by nimaa77** [comment]
Do you want some source code?

**Comment by waynelinks** [comment]
That would be very helpful, @nimaa77.  I'm still new in this game, figured source code/example would be a great help in moving forward. Thanks for replying.
