### ISSUE TITLE
How to I fetch common APIs?

### ISSUE THREAD

**Issue by ganeshrvel** [jaredpalmer/after.js#337]
## ❓Question
I have a set of APIs which are to be called when the app loads. My approach is to set those API values to redux store. How do I call these common apis just once I open the website?

This is my route:
```
export default [
  {
    path: '/',
    exact: true,
    component: Home,
  },
  {
    path: '/profile',
    exact: true,
    component: asyncComponent({
      loader: () =>
        import(/* webpackChunkName: "profile" */ '../../features/Profile'),
    }),
  },
];
```

Document.tsx
```
// Compile an initial state
const preloadedState = {};

// Create a new Redux store instance
const store = configureStore(preloadedState);

  static async getInitialProps({ renderPage, req }: InitialProps) {
    const data = await getAppConfig();

   store.dispatch(actionSetAppConfig(data));

    const page = await renderPage(
      (Root: () => React.ReactElement) => (props: object) => (
        <Provider store={store}>
            <App>
              <Root {...props} />
            </App>
        </Provider>
      )
    );

    return { ...page };
  }
```

When I do this I get this error:
```
Warning: Did not expect server HTML to contain the text node 'some api value' in <p>.
```

**Comment by nimaa77** [comment]
you have to send that data to the client and then on the client when you hydrate you use that data as initialState for redux store

**Comment by nimaa77** [comment]
https://github.com/jaredpalmer/after.js/blob/master/examples/with-redux/src/Document.js#L52
https://github.com/jaredpalmer/after.js/blob/master/examples/with-redux/src/client.js#L10

**Comment by ganeshrvel** [comment]
@nimaa77 Thanks for quick reply. I was able to fix the problem.
I have a question about the common api calls as well.

Right now I have added the API calls and store dispatch inside the **Document.tsx** getInitialProps method like this, is this the right approach? Or should I call the apis in the server.ts file and pass it to Document.tsx?

```
 private static async getInitialProps({ renderPage }: InitialProps) {
    const appConfig = await this.getAppConfig();
    store.dispatch(actionSetAppConfig(appConfig));

    const page = await renderPage(
      (Root: () => React.ReactElement) => (props: object) => (
        <Provider store={store}>
          <App>
            <Root {...props} />
          </App>
        </Provider>
      )
    );

    return { ...page };
  }

````

**Comment by nimaa77** [comment]
there is no right or wrong for this
but I personally prefer to handle it in `server.js` file, IMHO it's more readable

**Comment by nimaa77** [comment]
I'm going to close this issue feel free to re-open it if you want
