### ISSUE TITLE
Usage of prefetch and refetch

### ISSUE THREAD

**Issue by atulmy** [jaredpalmer/after.js#339]
## Not sure how to use `prefetch` and `refetch`, can we have an example❓

Also, with the recent version, the component is not mount until `getInitialProps` is awaited which impacts the responsiveness in the UI. Hopefully using `prefetch` / `refetch` can fix this.

**Comment by nimaa77** [comment]
`prefetch`: can help us for faster navigation, think about it as a way to download assets for different route and call it's `getInitialProps` ahead of time that user moves to that page

`refetch`: will call getInitialProps of the current page again

combine guess js with prefetch and you are going to be the superman :D

https://guess-js.github.io/

> Guess.js provides a collection of libraries for enabling machine-learning driven experience for the Web.

so basically it will use your google analytics data (when you are going to setup this, you will be asked for GA account details) + AI to determine which page should be prefetched (or which page have more chance to get visited after current page)
