### ISSUE TITLE
Add transitionBehavior prop so we can show loading state when getInitialProps is fetching data

### ISSUE THREAD

**Issue by atulmy** [jaredpalmer/after.js#340]
Please provide a way to revert behaviour of `getInitialProps` previous to https://github.com/jaredpalmer/after.js/pull/251 and how @jaredpalmer originally implemented.

As @dbbk had commented:
> I prefer to instantly transition and display skeleton screens, keeping the user on the old screen makes our app feel slow and unresponsive.

Strongly agree on this. Many of the projects depend on this flow and not the new flow (which might be useful for few only).

Please take Twitter as an example for proper routing.

**Comment by nimaa77** [comment]
sure why not

**Comment by nimaa77** [comment]
but wait what should we call it :)?
`<AfterXXXX />`

**Comment by atulmy** [comment]
A flag would be better than to have multiple `<After />` exports.

Perhaps `<After data={data} routes={routes} some="flag" />` to enable the delayed behaviour.

**Comment by jaredpalmer** [comment]
`transitionBehavior: blocking | instant`

**Comment by atulmy** [comment]
Yes, thanks that would be wonderful! ❤️

**Comment by atulmy** [comment]
Hey @nimaa77 just wondering if there is any ETA for this fix?

**Comment by nimaa77** [comment]
oh sorry 
I was a little busy

I'm working on it now

**Comment by nimaa77** [comment]
(sorry I'm a little sick these days will get back to this very soon)

**Comment by nimaa77** [comment]
we have a pull request for this

but I need some feedback about how this should work
so please read the description on #348 and give me feedback ...
