### ISSUE TITLE
How to match a common wild card parameter in the Router and display a common screen?

### ISSUE THREAD

**Issue by ganeshrvel** [jaredpalmer/after.js#342]
## ❓Question
I want to capture any url which ends with **/login** and show a popup dialog modal. How can I achieve that?

Something like this:
```javascript
<BrowserRouter>
  <Route path="*/login">
    <LoginModal />
  </Route>
  <Switch>
    <Route path="/page">
      <Page />
    </Route>
    <Route path="/">
      <Home />
    </Route>
  </Switch>
</BrowserRouter>;

```

**Comment by atulmy** [comment]
One way you can do this is by rendering `<Switch>` in your Home component.

```javascript
<BrowserRouter>
  <Switch>
    <Route path="/">
      <Home />
    </Route>
  </Switch>
</BrowserRouter>
```

```javascript
const Home= () => {
  return(
    <div>
      <h1>Home page</h1>

      <Switch>
        <Route path="/login">
          <LoginModal />
        </Route>
      </Switch>
    </div>
  )
}
```

**Comment by nimaa77** [comment]
you can use regex in `path` property, read more information about this in react-router docs

**Comment by ganeshrvel** [comment]
@nimaa77 Even if I do that, After.js will pick just one item out of the whole routing array right? As stated in my question I want to use a route to display a common component, something which is outside the switch statement as we commonly do it. 

How do I get this done in After.js?

**Comment by ganeshrvel** [comment]
@atulmy will it respect the SSR loading if I use your example, and what about the `<After data={} route={} />` component?

I tried something like this earlier and it through client and server html mismatch error.

**Comment by nimaa77** [comment]
> @atulmy will it respect the SSR loading if I use your example, and what about the `<After data={} route={} />` component?
> 
> I tried something like this earlier and it through client and server html mismatch error.

if you change or add something to `client.js` you have to also add it to the `Document.js` 
check `with-layout-component` example

**Comment by ganeshrvel** [comment]
could you give us an example how this whole thing can be done? Where do i fit the whole `<After data={data} routes={routes} />` in this example? Do I lose the async loading if I do that?

> ```js
> <BrowserRouter>
>   <Switch>
>     <Route path="/">
>       <Home />
>     </Route>
>   </Switch>
> </BrowserRouter>
> ```

**Comment by nimaa77** [comment]
so basically `<After />` is this 
```js
<Switch>
    <Route exact path="/" component={Home}>
    <Route path="/about-us" component={AboutUS} >
</Switch>
```

so this should do the job 

```js
<Route path="*/login">
  <LoginModal />
</Route>
<After />
```

**Comment by ganeshrvel** [comment]
Wow awesome!

If anyone else is looking for the answer for the same question this is what I did:
I had to set `exact` as `false` in the route. 

routing.ts
```javascript
export default [
  {
    path: '/home',
    exact: false,
    component: asyncComponent({
      loader: () =>
        import(/* webpackChunkName: "home" */ '../../Component/Home'), // required
      Placeholder: () => null, // this is optional, just returns null by default
    }),
  },
  // 404 route
  {
    component: PageNotFound,
  },
];
```

client.ts
```javascript
ensureReady(routes).then((data: any) =>
  hydrate(
    <BrowserRouter>
      <Provider store={store}>
        <Route path="*/login"}>
          <Login />
        </Route>
        <App>
          <After data={data} routes={routes} />
        </App>
      </Provider>
    </BrowserRouter>,
    root
  )
);
```

Document.ts
```javascript
const page = await renderPage(
      (Root: () => React.ReactElement) => (props: object) => (
        <Provider store={store}>
          <Route path="*/login" exact>
            <Login />
          </Route>
          <App>
            <Root {...props} />
          </App>
        </Provider>
      )
    );
```

**Comment by nimaa77** [comment]
(there is no need to set `webpackChunkName` after.js will take care of that)

**Comment by nimaa77** [comment]
I'm going to close this issue feel free to re-open it if you want
