### ISSUE TITLE
Clarification on the After.js flow with running getInitialProps on server side during routing.

### ISSUE THREAD

**Issue by jwrlee88** [jaredpalmer/after.js#349]
## ❓Question

Hi all, I currently have a page that routes to another page using `NavLink` from react-router-dom. 
It seems that when I navigate from `/pageA` to `/pageB` using `NavLink` my getInitialProps function in `/pageB` does not run on the server side, but rather the client side. This is a little problematic for me as I would like to fetch my data on the server side rather than client side.  

I know in Next.JS you use `nextjs/Link` to navigate around pages and it will fetch data on the serverside for you, but since After.js is using `React Router` I was wondering how we can achieve the same effect in After.js with React Router.

**Comment by nimaa77** [comment]
the `getInitialProps` get called on both `client-side` and the `server-side`

in the initial request, it gets called on the server and when the user navigates between pages it called from the browser (this is how `next` and `after` work)

next also has a `getServerSideProps` method that works in the way that you explained

Am I correct?

**Comment by jwrlee88** [comment]
Ah okay, thanks for the quick response!

**Comment by nimaa77** [comment]
we can implement `getServerSideProps` in aftet too :D

there are some edge cases that I'm currently thinking about, I will add the functionality when I get around with those
