### ISSUE TITLE
Possible Memory leak with After.JS 

### ISSUE THREAD

**Issue by jwrlee88** [jaredpalmer/after.js#351]
## 🐛 Bug report
Hey everyone, we have an After.js production app utilising SSR hosted on Digital Ocean node with a 2GB Memory. We use Docker, Kubernetes and Rancher to manage deployments.

We have reason to believe that there is a memory leak of some sort happening within After.js. 

This is a screenshot of our current metrics measured by Grafana. As you can see the Memory keeps climbing in a linear fashion. Hovering over the data points, here is an example of the rate that the memory is increasing by:

15:59 - 459 MiB
16:00 - 466 MiB
16:01 - 473 MiB
16:02 - 479 MiB
16:03 - 489 MiB

And so on. 

The continual rise of memory overtime kills the DO node that the webapp is running on and crashes the node because it is out of memory. 

![rancher](https://user-images.githubusercontent.com/39804005/83567251-4fbac280-a4ef-11ea-8839-588bedbe197f.png)

Keep in mind, that at time of writing this (16:42pm EST) - we made sure that nobody was on the site and that there was no traffic since (15:41pm EST). What this tells us is that the Node application running is leaking memory. We can prove this by looking at the API logs which record the ip address and the time the request was made. Screenshot provided below:

![api logs](https://user-images.githubusercontent.com/39804005/83567831-3e25ea80-a4f0-11ea-9849-f1f620876ef6.png)

Even though nobody was on the site for the span of an hour - the memory usage clearly kept increasing. 

Is there anyway I can investigate how to find the leak and where to look? I realize that this is an odd report - but something has to be happening within After.js for us to experience this behaviour.

### Current Behavior

After.JS application running on production mode is leaking memory even though no one is using the production site.

### Expected behavior

The memory should not be leaking. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            | ^16.10.2
| After.js         | 3.0.3-canary.0 - also noticed the same behaviour with 3.0.2
| Razzle           | ^3.1.0
| Razzle Plugins   | 3.1.0
| TypeScript       | N/A
| Node             | 11.4-alpine
| Browser          | Chrome

**Comment by nimaa77** [comment]
Ummm can give me more info by creating a sample app with this problem?
