### ISSUE TITLE
Scrolling to top disable when search/hash changes?

### ISSUE THREAD

**Issue by march08** [jaredpalmer/after.js#364]
## ❓Can I enable the scroll to top feature only on location.pathname changes? 

E.g., I just want to change the url like so: `history.replace({ search: '?page=10' })` without scrolling to top.

The readme doesn't say anything so is there any such configuration? Would be nice, otherwise I am fine with my implementation, I just wanted to avoid it if there is a built in solution. Cheers!

**Comment by march08** [comment]
Ok I guess this might be an issue?

https://github.com/jaredpalmer/after.js/blob/master/packages/after.js/src/After.tsx#L94

`      if (
        (prevState.currentLocation &&
          prevState.currentLocation.pathname) !== location.pathname &&
        // Only Scroll if scrollToTop is not false
        scrollToTop.current === true &&
        instantMode === true
      ) {
        window.scrollTo(0, 0);
      }
`
should be
===> 

`      if (
        prevState.currentLocation &&
        prevState.currentLocation.pathname !== location.pathname &&
        // Only Scroll if scrollToTop is not false
        scrollToTop.current === true &&
        instantMode === true
      ) {
        window.scrollTo(0, 0);
      }
`

**Comment by nimaa77** [comment]
hello, you can disable the scroll to top thing easily 
just follow this part of the README
https://github.com/jaredpalmer/after.js#disable-auto-scroll-for-a-specific-page

**Comment by march08** [comment]
> hello, you can disable the scroll to top thing easily
> just follow this part of the README
> https://github.com/jaredpalmer/after.js#disable-auto-scroll-for-a-specific-page

I want toe scroll top, but it works even if only search or hash params change which I don't really want. 

e.g. 
`/cars` => `/cars?pricelt=10000` scrolls, I've copied part of the code which I think is a bug, can you verify that?

**Comment by march08** [comment]
I've created PR @jaredpalmer @nimaa77 https://github.com/jaredpalmer/after.js/pull/365

**Comment by nimaa77** [comment]
hey I just released a new version

https://github.com/jaredpalmer/after.js/releases/tag/v3.1.2

check it out and give me some feedback

**Comment by march08** [comment]
> hey I just released a new version
> 
> https://github.com/jaredpalmer/after.js/releases/tag/v3.1.2
> 
> check it out and give me some feedback

ok awesome, works as expected!

**Comment by nimaa77** [comment]
thanks for your contribution and GG 😎
