### ISSUE TITLE
history and location in getInitialProps

### ISSUE THREAD

**Issue by mskarimi** [jaredpalmer/after.js#368]
## ❓Question / 🐛 Bug
base on `README.md` we can see `history` and `location.pathname` in `getInitialProps` on the server, but both of them are `undefined`?
I need to access the current request URL `query` param in `getInitilaProps`

**Comment by march08** [comment]
Can verify that it is missing on the server side.

In the meantime, you can access the query like so `ctx.req?.query` @mskarimi

**Comment by mskarimi** [comment]
you are right
thanks
@march08

**Comment by pmbednarczyk** [comment]
They are all undefined for me as well. Even the req.query:
![image](https://user-images.githubusercontent.com/16899307/89122049-792ea500-d4c4-11ea-9abe-950f233fe546.png)
Am i doing something wrong?

**Comment by mskarimi** [comment]
History and location only work in client side rendering, and req is available in server side rendering

**Comment by pmbednarczyk** [comment]
Oh ok, thank you :)
I've got current location url from "match.url" :)
