### ISSUE TITLE
Multiple entries for multi-page application

### ISSUE THREAD

**Issue by batusai513** [jaredpalmer/after.js#371]
## Can I modify after.js to be able to get a multipage application?

It would be possible to create [Multi-page applications](https://webpack.js.org/concepts/entry-points/#multi-page-application) using this awesome library?, the idea is to have the `getInitialProps` to get the data for each page but one thing I don't want/need is to have client side routing, but handle all the routing server side using a node server, I have changed some configuration on `razzle.config.js` to inject each entry point manually but I'm getting some errors.
```js
// razle.config.js
const path = require('path');

module.exports = {
  modify: (config, { target, dev }, webpack) => {
    // do something to config
    if (target === 'web') {
      const devClient = config.entry.client[0];
      delete config.entry.client;
      config.entry.home = [
        devClient,
        path.join(__dirname, path.resolve('/src/home/client.js')),
      ];

      config.entry.about = [
        devClient,
        path.join(__dirname, path.resolve('/src/about/client.js')),
      ];
    }
    return config;
  },
};
```

```js
//index.js
import express from 'express';

let root = require('./home/server').default;
let about = require('./about/server').default;
// let server = require('./server').default;

if (module.hot) {
  module.hot.accept('./server', function() {
    console.log('🔁  HMR Reloading `./server`...');
    try {
      app = require('./server').default;
    } catch (error) {
      console.error(error);
    }
  });
  console.info('✅  Server-side HMR Enabled!');
}

const port = process.env.PORT || 3000;

const app = express();
app.disable('x-powered-by');
app.use('/static', express.static(process.env.RAZZLE_PUBLIC_DIR));
app.use('/', root);
app.use('/about', about);

export default app.listen(port, function(err) {
  if (err) {
    console.error(err);
    return;
  }
  console.log(`> Started on port ${port}`);
});

```

For each page I have created a folder with a set of files (client.js, server.js, routes.js) to handle each page separately.
```js
// home/client.js
import React from 'react';
import { hydrate } from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import { ensureReady, After } from '@jaredpalmer/after';
import './client.css';
import routes from './routes';

ensureReady(routes).then(data => {
  return hydrate(
    <BrowserRouter>
      <After data={data} routes={routes} />
    </BrowserRouter>,
    document.getElementById('root')
  );
});

if (module.hot) {
  module.hot.accept();
}
```

```js
// home/server.js
import express from 'express';
import { render } from '@jaredpalmer/after';
import routes from './routes';

const assets = require(process.env.RAZZLE_ASSETS_MANIFEST);
const chunks = require(process.env.RAZZLE_CHUNKS_MANIFEST);

const router = express.Router();
router.get('/', async (req, res) => {
  try {
    const html = await render({
      req,
      res,
      routes,
      assets,
      chunks,
    });
    console.log(html);
    res.send(html);
  } catch (error) {
    console.error(error);
    res.json({ message: error.message, stack: error.stack });
  }
});

export default router;
```

```js
// home/routes.js
import React from 'react';
import { asyncComponent } from '@jaredpalmer/after';

export default [
  {
    path: '/',
    exact: true,
    component: asyncComponent({
      loader: () => import('../components/home/Home'), // required
      Placeholder: () => <div>...LOADING...</div>, // this is optional, just returns null by default
    }),
  },
];
```
Same goes for the about page, but the routes.js looks like this:
```js
// about/routes.js
import React from 'react';
import { asyncComponent } from '@jaredpalmer/after';

export default [
  {
    path: '/about',
    component: asyncComponent({
      loader: () => import('../components/about/About'), // required
      Placeholder: () => <div>...LOADING...</div>, // this is optional, just returns null by default
    }),
  },
];
```
When running `yarn start`, everything runs ok, but when I try to navigate into one of the routes, I get an error:
```
TypeError: Cannot read property 'css' of undefined at exports.AfterStyles (/Users/richardroncancio/projects/after.js/examples/basic/node_modules/@jaredpalmer/after/src/Document.tsx:70:19)
```
I've tracked the error to https://github.com/jaredpalmer/after.js/blob/9f94ed0bc2b7bbfbff2bb5adf1e4cc050e1861a6/packages/after.js/src/Document.tsx#L69
In here the error is obvious because the client entry point does not exist anymore, so the question would be, What Do I need to change in order to get the entrypoint name dynamically in here?

Thanks in advanced for any help you can provide.

**Comment by nimaa77** [comment]
hello
what I understand is that you don't want to rehydrate on the client-side and you only use after.js on the server-side to work like a template engine that renders react and prints out HTML!

in this case, you may want to use "granular-chunking", it's not going to give you the same thing exact thing that multi-entry config in webpack will do, but results should be the same.

https://web.dev/granular-chunking-nextjs/#improved-chunking

and then you create a custom `Document.js` file and you don't send the JS files to the client (so no rehydration should happen)

```jsx
import React  from "react"
import { AfterRoot } from "@jaredpalmer/after"

function Document({ helmet }) {
  const htmlAttrs = helmet.htmlAttributes.toComponent();
  const bodyAttrs = helmet.bodyAttributes.toComponent();

  return (
    <html {...htmlAttrs}>
      <head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {helmet.title.toComponent()}
        {helmet.meta.toComponent()}
        {helmet.link.toComponent()}
        <AfterStyles />
      </head>
      <body {...bodyAttrs}>
        <AfterRoot />
      </body>
    </html>
  );
}

Document.getInitialProps = async ({ renderPage }) => {
  const page = await renderPage();
  return { ...page };
};
```

**Comment by nimaa77** [comment]
when you run `yarn build` in the build folder you can see a file called `assets.json`

it looks like this:
```json
{
  "client": {
    "css": "/static/css/foo.css",
  }
}
```

actually `assets.client.css` have the path for the CSS file on your server you don't have the "client" it's going to be `undefined`.

but styles object that has CSS for code splitted routes may help you with your current webpack config

```jsx
import React  from "react"
import { AfterRoot, useAfterContext } from "@jaredpalmer/after"

function Document({ helmet }) {
  const htmlAttrs = helmet.htmlAttributes.toComponent();
  const bodyAttrs = helmet.bodyAttributes.toComponent();

  const { styles } = useAfterContext()

  return (
    <html {...htmlAttrs}>
      <head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {helmet.title.toComponent()}
        {helmet.meta.toComponent()}
        {helmet.link.toComponent()}

        {styles.map(path => (
          <link key={path} rel="stylesheet" href={path} />
        ))}

      </head>
      <body {...bodyAttrs}>
        <AfterRoot />
      </body>
    </html>
  );
}

Document.getInitialProps = async ({ renderPage }) => {
  const page = await renderPage();
  return { ...page };
};
```

**Comment by batusai513** [comment]
> hello
> what I understand is that you don't want to rehydrate on the client-side and you only use after.js on the server-side to work like a template engine that renders react and prints out HTML!
> 
> in this case, you may want to use "granular-chunking", it's not going to give you the same thing exact thing that multi-entry config in webpack will do, but results should be the same.

In this case, I want the client Rehydration, the only thing I don't want is client side routing (react-router), because there are some complex user interactions, I wanted to go the multi-entry way because that way I will only load what's actually needed for that specific page, I've been looking deeper at the code and thinking on maybe adding a name or identifier on the route configuration, something like this:
```js
// home/routes.js
import React from 'react';
import { asyncComponent } from '@jaredpalmer/after';

export default [
  {
    path: '/',
    exact: true,
    identifier: 'home',
    component: asyncComponent({
      loader: () => import('../components/home/Home'), // required
      Placeholder: () => <div>...LOADING...</div>, // this is optional, just returns null by default
    }),
  },
];
```
and somehow pass it in the render as a prop, maybe, then I can know which page I'm and get the proper css file, If I can't get it to work, then I will go with this granular chunking strategy.

Thanks for your help.

**Comment by nimaa77** [comment]
> > hello
> > what I understand is that you don't want to rehydrate on the client-side and you only use after.js on the server-side to work like a template engine that renders react and prints out HTML!
> > in this case, you may want to use "granular-chunking", it's not going to give you the same thing exact thing that multi-entry config in webpack will do, but results should be the same.
> 
> In this case, I want the client Rehydration, the only thing I don't want is client side routing (react-router), because there are some complex user interactions, I wanted to go the multi-entry way because that way I will only load what's actually needed for that specific page, I've been looking deeper at the code and thinking on maybe adding a name or identifier on the route configuration, something like this:
> 
> ```js
> // home/routes.js
> import React from 'react';
> import { asyncComponent } from '@jaredpalmer/after';
> 
> export default [
>   {
>     path: '/',
>     exact: true,
>     identifier: 'home',
>     component: asyncComponent({
>       loader: () => import('../components/home/Home'), // required
>       Placeholder: () => <div>...LOADING...</div>, // this is optional, just returns null by default
>     }),
>   },
> ];
> ```
> 
> and somehow pass it in the render as a prop, maybe, then I can know which page I'm and get the proper css file, If I can't get it to work, then I will go with this granular chunking strategy.
> 
> @nimaa77 Do you think it's possible this Idea?
> 
> Thanks for your help.

yes :D

we have this already.

https://github.com/jaredpalmer/after.js/tree/master/packages/babel-plugin-after

that `styles` array you get from `useAfterContext()` should give you the data that you need.

if it didn't work send me the `chunks.json` file in the `build` directory (you must run the `yarn build` command first)

**Comment by batusai513** [comment]
@nimaa77 What I ended up doing was to pass the name of the entry via extra prop on the render method:
```js
// home/server.js
import express from 'express';
import { render } from '@jaredpalmer/after';
import routes from './routes';

const assets = require(process.env.RAZZLE_ASSETS_MANIFEST);
const chunks = require(process.env.RAZZLE_CHUNKS_MANIFEST);

const router = express.Router();
router.get('/', async (req, res) => {
  try {
    const html = await render({
      req,
      res,
      routes,
      assets,
      chunks,
      name: 'home',
    });
    res.send(html);
  } catch (error) {
    console.error(error);
    res.json({ message: error.message, stack: error.stack });
  }
});

export default router;
```
```js
// about/server.js
import express from 'express';
import { render } from '@jaredpalmer/after';
import routes from './routes';

const assets = require(process.env.RAZZLE_ASSETS_MANIFEST);
const chunks = require(process.env.RAZZLE_CHUNKS_MANIFEST);

const router = express.Router();
router.get('/about', async (req, res) => {
  try {
    const html = await render({
      req,
      res,
      routes,
      assets,
      chunks,
      name: 'about',
    });
    res.send(html);
  } catch (error) {
    console.error(error);
    res.json({ message: error.message, stack: error.stack });
  }
});

export default router;
```

I have also modified the Document.js and get the assets like this
```js
assets[name].css && React.createElement("link", { rel: "stylesheet", href: assets[name].css })

assets[name].js && (React.createElement("script", { type: "text/javascript", src: assets[name].js, defer: true, crossOrigin: "anonymous" }))));
```

This works, but only on a production build, on development it is mixing things up, it renders well on the server, when navigating to `/`, it sends the actual root home content, but when the client bundle loads it's loading the about router when navigating to the `/` path, and it is replacing the html with the 404 content.

this is the assets.json for production
```json
{
  "about": {
    "css": "/static/css/bundle.36d04d42.css",
    "js": "/static/js/bundle.9447ae47.js"
  },
  "client": {
    "css": "/static/css/bundle.36d04d42.css",
    "js": "/static/js/bundle.ec5278ef.js"
  },
  "components-about/About": {
    "js": "/static/js/components-about/About.b85d6206.chunk.js"
  },
  "components-home/Home": {
    "css": "/static/css/components-home/Home.2f97ec2d.chunk.css",
    "js": "/static/js/components-home/Home.9709ebca.chunk.js"
  },
  "home": {
    "css": "/static/css/bundle.36d04d42.css",
    "js": "/static/js/bundle.561b2094.js"
  },
  "": {
    "json": "/../chunks.json",
    "txt": [
      "/static/js/bundle.561b2094.js.LICENSE.txt",
      "/static/js/bundle.9447ae47.js.LICENSE.txt",
      "/static/js/bundle.ec5278ef.js.LICENSE.txt"
    ],
    "svg": "/static/media/react.be7b83d4.svg"
  }
}
```

this is the assets.json on development
```json
{
  "about": { "js": "http://localhost:3001/static/js/bundle.js" },
  "components-about/About": {
    "js": "http://localhost:3001/static/js/components-about/About.chunk.js"
  },
  "components-home/Home": {
    "js": "http://localhost:3001/static/js/components-home/Home.chunk.js"
  },
  "home": { "js": "http://localhost:3001/static/js/bundle.js" },
  "vendors~components-home/Home": {
    "js": "http://localhost:3001/static/js/vendors~components-home/Home.chunk.js"
  },
  "": {
    "json": "http://localhost:3001/../chunks.json",
    "svg": "http://localhost:3001/static/media/react.be7b83d4.svg"
  }
}
```

**Comment by nimaa77** [comment]
that's really complicated we can make it waaaay more simpler

can you send me the chunks.json file!

**Comment by jaredpalmer** [comment]
Multi entry is something I eventually want to support. It will allow after.js to scale better because Razzle build speed will not increase with more code. You also wouldn’t need to recompile the whole app just for a single route change, just that entry point.

**Comment by batusai513** [comment]
@nimaa77 
chunks.json
```json
{
  "about": {
    "css": [],
    "js": [
      "http://localhost:3001/static/js/bundle.js",
      "http://localhost:3001/static/js/bundle.js.map"
    ]
  },
  "components-about/About": {
    "css": [],
    "js": [
      "http://localhost:3001/static/js/components-about/About.chunk.js",
      "http://localhost:3001/static/js/components-about/About.chunk.js.map"
    ]
  },
  "components-home/Home": {
    "css": [],
    "js": [
      "http://localhost:3001/static/js/vendors~components-home/Home.chunk.js",
      "http://localhost:3001/static/js/vendors~components-home/Home.chunk.js.map",
      "http://localhost:3001/static/js/components-home/Home.chunk.js",
      "http://localhost:3001/static/js/components-home/Home.chunk.js.map"
    ]
  },
  "home": {
    "css": [],
    "js": [
      "http://localhost:3001/static/js/bundle.js",
      "http://localhost:3001/static/js/bundle.js.map"
    ]
  }
}
```

**Comment by batusai513** [comment]
@nimaa77 just to make things simpler, I have created a example repo https://github.com/batusai513/after-basic-multipage
