### ISSUE TITLE
ensureReady return type does not match the <After /> data property

### ISSUE THREAD

**Issue by rvanlaarhoven** [jaredpalmer/after.js#373]
### Current Behavior

While using the After.js Basic example in a typescript app, the following type error is shown on https://github.com/jaredpalmer/after.js/blob/master/examples/basic/src/client.js#L11:

```
Type 'Promise<any>[]' is missing the following properties from type 'ServerAppState': afterData, initialData
```

This happens because the return type on https://github.com/jaredpalmer/after.js/blob/a720d34f64c71bc4e5690c62bf6d9ebc66197260/packages/after.js/src/ensureReady.ts#L29 is invalid and should probably return the `ServerAppState`.

I've updated this to `ServerAppState` locally, but then I end up with the following type error on the `<After />` component:

```
Property 'transitionBehavior' is missing in type '{ data: ServerAppState; routes: { path: string; component: typeof App; }[]; }' but required in type 'Readonly<Pick<AfterpartyProps, "data" | "routes" | "transitionBehavior">>'
```

I'm not sure how to proceed here, since I do not know what the purpose of this transitionBehavior should be.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            | 16.13.1|
| After.js         | 3.1.2 |
| Razzle           | 3.1.5 |
| TypeScript       | 3.9.7 |
| Node             | 12.8.1 |

**Comment by rvanlaarhoven** [comment]
Making `transitionBehavior` optional would probably fix the issue. See also https://github.com/jaredpalmer/after.js/pull/375

**Comment by abiro** [comment]
This seems to be still an issue.
