### ISSUE TITLE
I have to restart the app every time I update a page getInitialProps function

### ISSUE THREAD

**Issue by batusai513** [jaredpalmer/after.js#374]
### Current Behavior

Whenever I update a page getInitialProps I have to restart the server because it's not getting the new code changes

### Expected behavior

When I update getInitialProps and reload the page, it should call the latests code updates and reflect them on the props passed to the component

### Additional context

I'm using functional components for the Document and page components

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            | 16.3.1
| After.js         | 3.1,2
| Razzle           | 3.1.0
| Razzle Plugins   | razzle-plugin-scss@3.1.5
| TypeScript       |
| Node             | 14.0
| Browser          | All
| npm/Yarn         | yarn 1.22
| Operating System | macOS catalina 10.15.5

**Comment by fivethreeo** [comment]
This should be a razzle issue, but it is a hard issue to debug.
