### ISSUE TITLE
Nested Routing

### ISSUE THREAD

**Issue by alexnm** [jaredpalmer/after.js#38]
How could the behavior in _routes.js be done in smaller sections of the application? I like the idea of a single top level router mechanism, but how would you implement routing inside one of the pages (like '/about', '/about/foo', '/about/bar') without duplicating the code and adding them as top level routes?

PS: I was curios to test this out with a Layout component so I can do an example PR maybe it makes more sense to talk about that one.
PS2: Awesome work, I love this idea

**Comment by jaredpalmer** [comment]
Are you thinking about Nested Data too?

**Comment by alexnm** [comment]
Not my first thought, but thinking about it now.

**Comment by jaredpalmer** [comment]
We could move to using react-router-config and use Airbnb's nesting technique

**Comment by alexnm** [comment]
I'm confused, isn't the current solution using react-router-config? and I'm not familiar with Airbnb's nesting technique, can you share a link?

**Comment by pronevich** [comment]
@alexnm some ideas were explained here https://medium.com/airbnb-engineering/server-rendering-code-splitting-and-lazy-loading-with-react-router-v4-bfe596a6af70

**Comment by jaredpalmer** [comment]
After is not actually using react-router-config right now. Although I think we may end up there. Key difference between react-router-config is that it has a top level Root component vs. After has a flat array. Right now After.js takes care of that with _app.js. Move to RRC would mean we may need to lift / move around _app.js's state.
