### ISSUE TITLE
Modern React

### ISSUE THREAD

**Issue by Aslemammad** [jaredpalmer/after.js#385]
## 🚀 Feature request
Hello,I'm @aslemammad and I love After.js, It's a cool tool. I'm a beginner and I read the source, and I think the class components should turn to functional components and other new react features. Thanks

**Comment by Aslemammad** [comment]
I think I can take its PR. No problem?

**Comment by nimaa77** [comment]
it's impossible to do achieve same thing with function components since there is no `static getDerivedStateFromProps` on the function components
