### ISSUE TITLE
Compatibility with ESM builds?

### ISSUE THREAD

**Issue by jwrlee88** [jaredpalmer/after.js#387]
## ❓Question

Hello again,

I am in the middle of transitioning part of an old React project that used React Boilerplate to After.JS (specifically just the landing pages so we can take advantage of SSR that After.js offers). 

My old project uses [ReactStrap](https://reactstrap.github.io/) for some components such as modals, and buttons and what not. 

When I try to run my project, I get this error: 

```
app_react      | yarn run v1.12.3
app_react      | $ razzle start
app_react      |  WAIT  Compiling...
app_react      | 
app_react      | Using .babelrc defined in your app root
app_react      | Using .babelrc defined in your app root
app_react      | ℹ Compiling Client
app_react      | ✔ Client: Compiled with some errors in 6.47s
app_react      | ℹ Compiling Server
app_react      | ✔ Server: Compiled with some errors in 1.72s
app_react      | ✅  Server-side HMR Enabled!
app_react      | > Started on port 3000
app_react      | /app/node_modules/reactstrap/es/ModalBody.js:1
app_react      | (function (exports, require, module, __filename, __dirname) { import _extends from "@babel/runtime/helpers/esm/extends";
app_react      |                                                                      ^^^^^^^^
app_react      | 
app_react      | SyntaxError: Unexpected identifier
app_react      |     at new Script (vm.js:84:7)
app_react      |     at createScript (vm.js:264:10)
app_react      |     at Object.runInThisContext (vm.js:312:10)
app_react      |     at Module._compile (internal/modules/cjs/loader.js:684:28)
app_react      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
app_react      |     at Module.load (internal/modules/cjs/loader.js:620:32)
app_react      |     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
app_react      |     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
app_react      |     at Module.require (internal/modules/cjs/loader.js:657:17)
app_react      |     at require (internal/modules/cjs/helpers.js:22:18)
```
which I am aware that this error happens when Babel / Webpack is not configured to handle ESM builds. 

Are there plans to support ESM builds any time soon? I saw this [closed pull request from a while back](https://github.com/jaredpalmer/after.js/pull/246) that mentioned ESM builds. If its not in the plans in the near future, no worries, I will figure something else out :) 

All the best.

**Comment by nimaa77** [comment]
hey, this issue is related to your build system configuration

if you are using razzle for webpack tooling create a new issue on the razzle repo (https://github.com/jaredpalmer/razzle)
