### ISSUE TITLE
Create a contributing guide

### ISSUE THREAD

**Issue by dielduarte** [jaredpalmer/after.js#39]
Hello! first, congratulations for that amazing project !

I'm thinking that's a good way to help new contributors to understand the architecture and patterns of the project, before start code something...

What do you think about it? and how I could help you with that ?

Thanks!

**Comment by RxAssim** [comment]
@dielduarte You're right. A contributing guide is important to maintain and improve the framework.

**Comment by tanvirraj** [comment]
agree

**Comment by jaredpalmer** [comment]
Yup will do
