### ISSUE TITLE
Warning: Did not expect server HTML to contain a <p> in <div>.

### ISSUE THREAD

**Issue by suvojitseal** [jaredpalmer/after.js#397]
### Current Behavior
I am using redux store inside _**static getInitialProps**_ to use it inside component in ssr. There I am getting this warning.

I found some solutions in stackoverflow and and github issues, there it is mentioned that because of space inside root element it is happening. But in case of After js there <AfterData> tag is been used where `<div id="root">${markup}</div> `is been used. Another resource said that the issue is from react end because there is a dom difference between CSR and SSR. How to solve this problem?

Here are the link of related issues:
1. [stackoberflow](https://stackoverflow.com/questions/45350360/react-16-warning-warning-js36-warning-did-not-expect-server-html-to-contain-a)
2. [github](https://github.com/vercel/next.js/issues/8773)
3. [github](https://github.com/vercel/next.js/issues/5367)

Here are some snippets of my project

- **_containers/Home/index.js_**

```js
import { connect } from 'react-redux';

import { getCategoriesBy } from '../../state-manager/action/categoryAction';
import Home from './Home';

const mapStoreToProps = state => ({
    categories: state.category.categories
})

const mapDispatchToProps = dispatch => ({
    getCategoriesBy: (params) => dispatch(getCategoriesBy(params))
})


export default connect(mapStoreToProps, mapDispatchToProps)(Home);
```

- **_containers/Home/Home.js_**

```js
import React from 'react';

import Header from '../../common/Header';
import Footer from '../../common/Footer';
import Slider from './components/Slider';

import { getCategoriesBy } from '../../state-manager/action/categoryAction';

class Home extends React.Component {

    static async getInitialProps({ req, res, match, store }) {
        const params = {
            pagination: {
                page: 1,
                perPage: 50
            }
        };

        store.dispatch(getCategoriesBy(params));
    }

    constructor(props) {
        super(props);
        this.state = {
            isCSR: false,
            ssr: true
        };
    }

    componentDidMount() {
        if (window !== 'undefined') {
            this.setState({
                isCSR: true,
            });
        }
    }

    render() {
        const { categories, loading } = this.props;
        return (
            <div className="boxes-wrapper">
                <div id="page-body">
                    <Header></Header>
                    <div>
                        {categories.length > 0 && categories.map((el, key) => {
                            return <p key={key}>{el.name} ss</p>
                        })}
                    </div>
                    {this.state.isCSR && <Slider message={'Hello Slider'}></Slider>}
                    <Footer />
                </div>
            </div>
        );
    }
}

export default Home;
```

- **_store-manager/action/categoryAction.js_**

```js
import * as actions from '../actionTypes';
import http from '../../utils/api';

export const setCategories = (res) => ({
    type: actions.LIST_CATEGORY_SUCCESS,
    payload: {...res.data.payload}
})

export const getCategoriesBy = (params) => dispatch => {
    dispatch({
        type: actions.LIST_CATEGORY
    })
    return http({
        method: 'POST',
        url: '/category/search',
        data: params
    })
    .then(res => {
        dispatch({
            type: actions.LIST_CATEGORY_SUCCESS,
            payload: {...res.data.payload}
        })
        return {...res.data.payload}
    }).catch(error => {
        dispatch({
            type: actions.LIST_CATEGORY_FAILURE,
            payload: { error }
        })
        return { error }
    })
};
```

I followed rest of the codes of project from after.js redux example and custom document snippets from after.js readme doc

Screenshot of error:
![Screenshot from 2020-09-20 13-01-08](https://user-images.githubusercontent.com/19174125/93706339-d9e07280-fb42-11ea-8189-56b7ede612ba.png)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            |16.13.1
| After.js         |0.8.2
| Razzle           |^3.1.0
|Redux            | ^4.0.5
|React Redux |^7.2.1
|React Router DOM|5.2.0
| Razzle Plugins   |
| TypeScript       |
| Node             |10.21.0
| Browser          |Chrome 85.0.4183.102 
| npm/Yarn         | npm 6.14.4
| Operating System | Ubuntu 20.04

Thanks in advance
@jaredpalmer

**Comment by nimaa77** [comment]
hi @suvojitseal 

can you create a repo with this error?
redux is really complicated and we should take look at different parts of the application, for example, you should send store state as initial redux store state to the client in the Document.js file and then on client.js you create a new store and you should pass the state that comes from document.js as the initial value of store ...

also, this example should help you a lot https://github.com/jaredpalmer/after.js/tree/master/examples/with-redux

**Comment by nimaa77** [comment]
I think the issue is fixed

fill free to reopen if you still have problems with redux and after.js

**Comment by suvojitseal** [comment]
Sorry to inform here that I solved the issue.
Its from my end, I forgot to add 
`const preloadedState = getSerializedData('preloaded_state');`
before store initializartion in client side.. that is why server side and client side state is getting mismatch. and generates different dom in different side.

Again extremely sorry to bother you. :(
