### ISSUE TITLE
can i use same node process multi site based on domain?

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#399]
## ❓Question
can i use same node process multi site based on domain?

thanks

**Comment by nimaa77** [comment]
hi, 

Do you wan to use one site on multiple domains with one instance of nodejs app running? if this is your answer, my question is "Yes, it's possible" 

if you are using express with after.js (all examples are using express) you can search for your question by appending express js to the end of it :D

> can i use same node process multi site based on domain express js

**Comment by maorkavod** [comment]
I manage to solve this by replacing the .env file with the "Add Params to getInitialProps" option. 
I raplaced the .env line to json object than make the same node procces to serve diffrent sites based on the hostname. like this: 

```
  .get('/*', async (req, res) => {
    try {
      let NODE_ENV = await import(`../envs/${req.hostname}.js`);
      const env = NODE_ENV.env();
      const html = await render({
        req,
        res,
        document: Document_,
        chunks,
        routes,
        assets,
        customThing : env
      });
      res.send(html);
    } catch (error) {
      console.log(error);
      res.json(error);
    }
  });
```
