### ISSUE TITLE
Recursive Data Fetching

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/after.js#4]
We would need to walk the tree 🚶‍♀️

**Comment by mohsen1** [comment]
> You basically just need to figure out which components you're planning to render

Rendering once to figure out what data needs to be fetched is something I did before. Not clean but it works. Only if React render could return a promise... 😬

**Comment by tamagokun** [comment]
I've used this in the past to accomplish data fetching for any component in a tree on the server: https://github.com/ctrlplusb/react-tree-walker 

Worked out really well.

**Comment by jaredpalmer** [comment]
Yeah that could work. 

@mjackson is `react-router-config` `matchRoutes` recursive? Should we be using that instead of the current implementation?

**Comment by dbbk** [comment]
@jaredpalmer I actually just implemented this in a project I'm working on, I've published it as an npm package, might be of help!

https://github.com/dbbk/react-data-fetching-components
