### ISSUE TITLE
How to use Afterjs with a custom server?

### ISSUE THREAD

**Issue by LahmerIlyas** [jaredpalmer/after.js#401]
Hi, thx for this awesome library. How can I use this library with a custom server without the need for razzle cli like in nextjs ?

**Comment by eran-pinhas** [comment]
Disclaimer - Just started using After.js

It seems that

1. `razzle-dev-utils` is listed as peer dependen of after.js. which I believe mean that it's embeded at some level in the library, though by searching in the repo it seems to be only the `razzle-dev-utils/logger`. But not sure what would you do in the build process.
2. From my understanding razzle should be used as an express.js `.use` handler . I would define this as a custom server but 🤷

**Comment by nimaa77** [comment]
@LahmerIlyas hey, I didn't understand your question

razzle is just a webpack configuration that we use for our examples, you can configure webpack yourself and at the end add after.js to your app.

if you decided to use razzle, anything related to server-side code will get handled from server.js and index.js and anything related to browser/client-side can be handled from the client.js


@eran-pinhas `razzle-dev-utils` is just a package which has some utilities for invariant, logger and ...
we only use logger (but it doesn't mean after.js is dependent on razzle, razzle dev tools is complicity different than what razzle dose)
