### ISSUE TITLE
How can I add getInitialProps to Layout Component (layout-component  example)

### ISSUE THREAD

**Issue by Volodymyrkohut** [jaredpalmer/after.js#402]
## ❓Question 
Thanks for the library. Really cool !!!

Layout component by default doesn't get  getInitialProps method. Is there any way to get it in it
There should be request  with initial project data (is authenticated user, some settings )

**Comment by Volodymyrkohut** [comment]
I use razzle.js. 
Nested routes would help. Is any example of it?

**Comment by nimaa77** [comment]
nested routes are not supported yet.
there is no official support for Layout component getInitalProps!. (but I can help you to implement it easily)

**Comment by Volodymyrkohut** [comment]
@nimaa77 I had seen roadmap (after.js 4.0). This version of library will get nested routes functionality.
When this release is planing ?

It would be good if you gave me some example of no official support for Layout component getInitalProps
I know, I can request initial data from Document.js and server.js, but maybe is better way ?

Thank you!

**Comment by Yamaha32088** [comment]
> nested routes are not supported yet. there is no official support for Layout component getInitalProps!. (but I can help you to implement it easily)

Would you be able to show me how to have getInitialProps inside of the Layout component? I have tried to add a `getInitialProps` function to my Layout component and then call it from within the `getInitialProps` function of Document which works however the data I am returning from the Layout component is not passed to the client side

**Comment by Volodymyrkohut** [comment]
@Yamaha32088 There is weak support here, I do not recommend using razzle and after js.
next js will be better to use

**Comment by Yamaha32088** [comment]
@Volodymyrkohut I would love to do that but we have a very large project that was built using Razzle and After.js that likely isn't going to be approved to convert to Next.js anytime soon.
