### ISSUE TITLE
Global modal window (example react-router-dom modal-gallery)

### ISSUE THREAD

**Issue by Volodymyrkohut** [jaredpalmer/after.js#403]
##  react-router-dom has good  example with global modal windows. Is any way do something like this in after.js ?
here link https://reactrouter.com/web/example/modal-gallery

thank you!

**Comment by nimaa77** [comment]
no, after.js controls the `location` prop and we can't implement this with after.js

you can use `with-react-router` example of razzle.js project and copy some code from `after.js` to handle getInitalProps and ...
