### ISSUE TITLE
Crawler is not getting correct metas

### ISSUE THREAD

**Issue by p32929** [jaredpalmer/after.js#412]
Hello, first of all, thanks for creating this framework. Today I just wanted to check the SSR capabilities of After.js. So, I created a new project and added react helmet in the **Home.js** and **About.js** files. Here's a screenshot of the code:

![Screenshot (300)](https://user-images.githubusercontent.com/6418354/102619238-51379980-4166-11eb-8c27-d85dd64dcf16.png)

Then I run the project using the `start` command and fired up **ngrok**. then ran facebook crawler on the app. but it was showing wrong meta tags.
Then again, I ran the `build` command then ran the `start:prod` command. But still, it was not showing correct meta tags.

![Screenshot_2020-12-18 Sharing Debugger - Facebook for Developers](https://user-images.githubusercontent.com/6418354/102619554-d4f18600-4166-11eb-8341-3c4655f107d1.png)

The title was supposed to be **My Title - HOME** but instead its showing **Welcome to the Afterparty**
Am I doing anything wrong? 

I would really appreciate if you could take some of your precious time to tell me how I get correct meta tags in social media crawlers using After.js
Thanks

**Comment by nimaa77** [comment]
hello
it's probably an afer.js bug, in the default [`Document.js`](https://github.com/jaredpalmer/after.js/blob/master/packages/after.js/src/Document.tsx#L25) file we render `<title>welcome to afterparty</title>` 

you can create a [custom document](https://github.com/jaredpalmer/after.js#custom-document) and remove the `<title />` from it and it will fix the problem

**Comment by nimaa77** [comment]
try to install the new version https://github.com/jaredpalmer/after.js/releases/tag/v3.1.3 and it will fix the issue
