### ISSUE TITLE
The starter project doesn't work

### ISSUE THREAD

**Issue by jakub-sarnowski-blinkhealth** [jaredpalmer/after.js#418]
### Current Behavior

I just wanted to test out After.js, installed `create-after-app`, created a project, started it, and boom!

### Expected behavior

I expected the starter project to work 😄 

### Reproducible example

No need, just follow the [quickstart](https://github.com/jaredpalmer/after.js#quickstart)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            |17.0.1
| After.js         |0.8.2
| Razzle           |3.1.0
| Razzle Plugins   |-
| TypeScript       |-
| Node             |v14.7.0
| Browser          |Chrome
| npm/Yarn         |Yarn 1.22.4
| Operating System |MacOS 10.15.7

**Comment by emilselroos** [comment]
Getting the following error:
`Cannot find module 'razzle-dev-utils/logger'`

**Comment by nimaa77** [comment]
this issue is fixed, feel free to re-open this if you still have problems
