### ISSUE TITLE
Error on using transitionBehavior="instant"

### ISSUE THREAD

**Issue by ATakaSKY** [jaredpalmer/after.js#423]
## 🐛 Bug report

I recently noticed in my application that while navigating from page A to page B, page A was getting called as well. This was avoided by adding `transitionBehavior="instant"` in After tag. With this change I was able to see that page A was not getting called when navigated to page B but some of the pages started breaking. Below is the error which I am getting:

![image](https://user-images.githubusercontent.com/17201629/109530220-7ccaee80-7adc-11eb-9aa6-e13801012e57.png)

This is the page's code that I am trying to navigate to:

```
import React, { useEffect, useState } from 'react';
import { useHistory } from 'react-router-dom';

import {
  debounce,
  saveSearchToLocalStorage,
  getItemFromLocalStorage,
} from 'common/utils/helpers';
import { stringifiedQueryParam } from 'common/utils/urlUtil';

function SearchPage() {
  console.log('search page request');
  const history = useHistory();
  const [recentSearches, setRecentSearches] = useState([]);

  const backToPage = () => {
    history.goBack();
  };

  useEffect(() => {
    const recentSearches = getItemFromLocalStorage('searchedHistory');

    if (recentSearches?.length) {
      setRecentSearches(recentSearches);
    }
  }, []);

  const debouncedSearch = debounce((e) => {
    console.log(e.target.value);

    // autosuggest API call
  }, 500);

  const searchChangeHandler = (e) => {
    e.persist();

    const searchValue = e.target.value;

    if (searchValue.trim() === '') return;

    if (e.keyCode === 13) {
      //save to LS
      saveSearchToLocalStorage('searchedHistory', {
        q: searchValue,
        id: Math.random() * 1000,
        searchType: 'manual',
      });

      const searchQuery = {
        q: searchValue,
        searchType: 'manual',
      };
      history.push(`search?${stringifiedQueryParam(searchQuery)}`);
    }

    debouncedSearch(e);
  };

  return (
    <div className="search-container">
      <div className="search-input">
        <span onClick={backToPage}>Back</span>
        <input
          type="text"
          placeholder="Search for products"
          onKeyDown={searchChangeHandler}
          className="search-input-text"
        />
        <ul className="search-results">
          {recentSearches.map((searchItem) => (
            <li className="search-item" key={searchItem.id}>
              <span>icon</span>
              <span>{searchItem.q}</span>
              <span>X</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default SearchPage;
```

And here's simple Link tag that I am using to navigate:

```
<Link to='/sitesearch'>
  <SearchIcon />
</Link>
```

Here's the route in rotutes.js:

```
{
    path: '/sitesearch',
    exact: true,
    component: asyncComponent({
      loader: () => import('./common/containers/MobileSearch'),
      Placeholder: <div>Loading filters...</div>,
      chunkName: 'Mobile search',
    }),
  }
```
### Suggested solution(s)

Should not result in an error. Not sure why this is happening as it works on some pages.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| React            | 16.13.1
| After.js         |  3.1.2
| Razzle           | 3.1.6
| Node             | 14.15.0
| Browser          | chrome
| npm/Yarn         | npm
| Operating System | macOS

**Comment by hadeeb** [comment]
`Placeholder` should be a component, not a JSX element.

https://github.com/jaredpalmer/after.js#code-splitting

https://github.com/jaredpalmer/after.js/blob/723cde87bcf94e66f9b94db9de14ab2e7c4d4095/packages/after.js/src/asyncComponent.tsx#L80

**Comment by nimaa77** [comment]
I'm going to close this issue feel free to re-open it if you want
