### ISSUE TITLE
Make After.js http server agnostic

### ISSUE THREAD

**Issue by jakub-sarnowski-blinkhealth** [jaredpalmer/after.js#431]
### Current Behavior

I can't use any other web framework like Fastify/Hapi, because After.js is bound to Express (usage of methods like `res.status` or `res.redirect` which are not available everywhere)

### Desired Behavior

It would be awesome if After.js would be http-server agnostic.

### Suggested Solution

Transition to Node's native request and response objects.

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

None

**Comment by nimaa77** [comment]
hello @jakub-sarnowski-blinkhealth

I'm not a backend developer and I have no experience with using Fastify/Hapi. you mean we use node.js http module?
what will happen to res.send/res.redirect and req/res objects after we make it http-server agnostic

**Comment by jakub-sarnowski-blinkhealth** [comment]
@nimaa77 
> you mean we use node.js http module?
Yes, I mean we should use the core Node.js http module, being more specific: req would be the Node.js [IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage), and res would be the [OutgoingMessage](https://nodejs.org/api/http.html#http_class_http_outgoingmessage). This way anyone using After.js could use any backend framework they like under the hood.

> what will happen to res.send/res.redirect and req/res objects after we make it http-server agnostic
They would be rewritten to use the core Node.js http module functions. For example:

```js
// express
res.send(html);

// core http
res.writeHead(200, { 'Content-Type': 'text/html' });
res.end(html);
```
