### ISSUE TITLE
Is After.js not meant to support the latest version of Razzle?

### ISSUE THREAD

**Issue by stevengrimaldo** [jaredpalmer/after.js#472]
## ❓Question
When installing a fresh create-after-app it uses a very old version 3.1.0, when upgrading to the latest 4.0.5 it immediately tells me i need to install ALL of the following addons before `yarn start` even works:

webpack
html-webpack-plugin
mini-css-extract-plugin
razzle-dev-utils (specifically complains about razzle-dev-utils/logger)
razzle-dev-utils
webpack-dev-server
babel-preset-razzle
webpack-dev-server

And even then after all of that it errors out and says

```
sswp> Handling Hot Module Reloading
Cannot find module 'undefined'
```

I'm already using After.js with Razzle 3.1.8 but want to upgrade Razzle to the latest so i can cleanly use typescript however it appears i can't use the latest version of Razzle with After.js (which i just spent time converting to).

I'm either looking for help using the latest version of Razzle with After OR figuring out how to use typescript with the older version of Razzle (3.1.8).

**Comment by tehraven** [comment]
https://github.com/jaredpalmer/after.js/pull/473

**Comment by stevengrimaldo** [comment]
Following up to this, the solution was downgrading webpack to a lower version along with additional code changes in the after js example code to conform with some newer changes from razzle.
