### ISSUE TITLE
Navlink activeClassName 

### ISSUE THREAD

**Issue by Ahmtdnz** [jaredpalmer/after.js#48]
How can we use activeClassName or activeStyle on Navlink ?

**Comment by jaredpalmer** [comment]
Same as always?

**Comment by Ahmtdnz** [comment]
Thanks for reply @jaredpalmer. I have a problem.

`<NavLink activeStyle={{color: 'red'}} to="/about"><h3>About</h3></NavLink>`
`<NavLink activeStyle={{color: 'red'}} to="/"><h3>Home</h3></NavLink>`

![screenshot at jan 17 18-00-59](https://user-images.githubusercontent.com/17492688/35049283-83480be8-fbb0-11e7-8534-ec417978cf5f.png)

Do you have any idea ?

**Comment by jaredpalmer** [comment]
Isn't there an exact prop that's required?

**Comment by Ahmtdnz** [comment]
It's working now. Thanks for help @jaredpalmer 

`<NavLink  activeStyle={{color: 'red'}} to="/about"><h3>About</h3></NavLink>`
`<NavLink exact activeStyle={{color: 'red'}} to="/"><h3>Home</h3></NavLink>`

![screenshot at jan 17 18-08-47](https://user-images.githubusercontent.com/17492688/35049572-7cfa9430-fbb1-11e7-9a49-9747ac973eb5.png)

We can close the issue.
