### ISSUE TITLE
Module not found: Can't resolve 'react-dom/unstable-native-dependencies'

### ISSUE THREAD

**Issue by Freddy03h** [jaredpalmer/after.js#49]
Hi ! I tried to use `react-native-web` in `after.js` but I've got this error : 
```
Module not found: Can't resolve 'react-dom/unstable-native-dependencies'
```

The error is located in a file from `react-native-web` but It doesn't seem to be directly link to this project.

I deleted `.babelrc` from my `after.js` project, delete all imports of `react-native-web`. Then adding in a component : 
```
import ReactDOMUnstableNativeDependencies from 'react-dom/unstable-native-dependencies'
```
And it produce the same error.

I also tried in a `next.js` project and it doesn't produce this error.

node v9.1.0
yarn 1.3.2
react & react-dom 16.2.0
after 0.5.1

**Comment by dcalhoun** [comment]
@jaredpalmer was there a resolution to this? I'm curious as I am attempting to resolve this same error in other projects.

**Comment by jaredpalmer** [comment]
I closed all issues on After.js See PR #83 

I am refactoring after.js and removing the build system. The result will be a library that can be used in tandem with razzle, with full compatibility.

**Comment by Freddy03h** [comment]
Ok, thank's for the answer ! 😃

**Comment by dcalhoun** [comment]
@jaredpalmer for posterity, I found the resolution to this problem in zeit/next.js#3738.
