### ISSUE TITLE
Get a better name

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/after.js#5]

**Comment by erikras** [comment]
I think this can be closed. 😆

**Comment by jaredpalmer** [comment]
Ehh i'd still like this not to be scoped to my name. I think that's super annoying.

**Comment by guilhermedecampo** [comment]
you could call it top (🔝 ) ;)

**Comment by AWebOfBrown** [comment]
BackStreet / BackStreets. 
Back = server-side-rendered, street = route.

**Comment by themre** [comment]
btw, link on npm (https://www.npmjs.com/package/@jaredpalmer/after) points to 404 page. missing `.js` at the end. It was really hard to find this package on google :D

**Comment by prichodko** [comment]
@themre, yup fixed it in #36 

I was trying to come up with some combination of `router` and `next` and I ended up with `rodex` 😄  (which is free on npm - https://www.npmjs.com/search?q=rodex). Thoughts @jaredpalmer?

**Comment by kapowaz** [comment]
What about `adjacent`? Looks like [somebody snagged the name a few years back](https://www.npmjs.com/package/adjacent) and hasn’t done anything with it, might be worth reaching out to see if they would be happy to release it?
