### ISSUE TITLE
Document how to do 404 not found

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/after.js#50]

**Comment by fuzzthink** [comment]
Any update on this?

**Comment by jaredpalmer** [comment]
Yeah I have to write up 2 components and modify _server.js. RouteStatus and an _error.js in lib.

**Comment by krazyjakee** [comment]
@jaredpalmer I see this is closed and you did something but what was it and how do I use it?

**Comment by nicholasess** [comment]
@jaredpalmer Do you can modify README.md to put the example for route 404?
I not found a way to set route :/

**Comment by bmcmurray** [comment]
@jaredpalmer ping, any update on how to handle non-200 status codes with razzle + after?

**Comment by maorkavod** [comment]
its worked! thanks!
but how do i redirect from other component getInitialProps to 404 in case of not found data from url props?
