### ISSUE TITLE
Does After.js support something similar to next/head?

### ISSUE THREAD

**Issue by steadweb** [jaredpalmer/after.js#511]
Ideally, functionality should exist to customize the metadata (tags) of each page separately. NextJS supports `next/head` which allows this. Does After.js have something similar?

Reference: https://nextjs.org/docs/api-reference/next/head

**Comment by MatthewPattell** [comment]
@steadweb just use `react-helmet`

**Comment by steadweb** [comment]
Thanks @MatthewPattell - without me looking, I'll need to check whether this supports SSR out the box.
