### ISSUE TITLE
Brotli compression algorithm support on production? 

### ISSUE THREAD

**Issue by maorkavod** [jaredpalmer/after.js#516]
## ❓Question
It would be great if there was a built-in support for Brotli compression.
I tried using the "razzle-plugin-brotli-gzip-zopfli" but with no success.

**Comment by anthonyp-usafacts** [comment]
I would leverage webpack for this instead of relying on After to do it for you. https://webpack.js.org/plugins/compression-webpack-plugin/#multiple-compressed-versions-of-assets-for-different-algorithm
