### ISSUE TITLE
Integration with the redux

### ISSUE THREAD

**Issue by apapacy** [jaredpalmer/after.js#52]
It is desirable to have "out of the box" integration with the redux. So far I can get it all from the next.js and can not with the after.js:
"next-redux-wrapper":  redux integration.
"next-routes": after.js's-like routes.

So. I tried to change ./src/_document.js, but it was replaced with  system default  ./src/_document.js on server start.

**Comment by jaredpalmer** [comment]
Yeah we need 2 things. A way to define a component that wraps everything on the client and a top level root component (first thing underneath BrowserRouter. That would solve this and a few other gotchas at the moment

**Comment by apapacy** [comment]
Good. By the way, Next.js does not use the react-router, but there is a plug-in that does this (next-routes). "Routes are just components and don't / should not have anything to do with folder structure. Static route configs are fine" - its right for next.js+next-routes.

**Comment by tejeshm** [comment]
> Yeah we need 2 things. A way to define a component that wraps everything on the client and a top level root component (first thing underneath BrowserRouter. That would solve this and a few other gotchas at the moment



Is there any example with this implementation??
