### ISSUE TITLE
Overriding or extending server config

### ISSUE THREAD

**Issue by saviomuc** [jaredpalmer/after.js#54]
Is there a way to create your own server config (Changing ports, using custom routes, enable specific middleware, etc.) ? I searched but couldnt find anything in the documentation or issues.

**Comment by dav-is** [comment]
At the very least, I found this: https://github.com/jaredpalmer/after.js/blob/01d3910ef49074ec435c8047586d5631ba0a7d5a/packages/after/lib/index.js#L6

**Comment by jaredpalmer** [comment]
You can create a file call server.js in the root of your project. You can start with this. 

```js
import App from './_app';
import routes from './_routes';
import Doc from './_document';
import loadInitialProps from './loadInitialProps';
import React from 'react';
import url from 'url';
import Helmet from 'react-helmet';
import ReactDOMServer from 'react-dom/server';
import express from 'express';
import { StaticRouter } from 'react-router-dom';
const assets = require(process.env.AFTER_ASSETS_MANIFEST);
const server = express();

const modPageFn = Page => props => <Page {...props} />;

server
  .disable('x-powered-by')
  .use(express.static(process.env.AFTER_PUBLIC_DIR))
  .get('/*', async (req, res) => {
    try {
      const context = {};
      const data = await loadInitialProps(routes, url.parse(req.url).pathname, {
        req,
        res,
      });

      const renderPage = (fn = modPageFn) => {
        const html = ReactDOMServer.renderToString(
          <StaticRouter location={req.url} context={context}>
            {fn(App)({ routes, data: data[0] })}
          </StaticRouter>
        );
        const helmet = Helmet.renderStatic();
        return { html, helmet };
      };

      const { html, ...docProps } = await Doc.getInitialProps({
        req,
        res,
        assets,
        renderPage,
        data: data[0],
      });

      const doc = ReactDOMServer.renderToStaticMarkup(<Doc {...docProps} />);
      res.send(
        `<!doctype html>` +
          doc.replace('DO_NOT_DELETE_THIS_YOU_WILL_BREAK_YOUR_APP', html)
      );
    } catch (error) {
      res.json(error);
    }
  });

export default server;
```

**Comment by saviomuc** [comment]
Thanks for the example. I feel like this is a pretty opinionated and very specific setup to overwrite the server config. I guess this file could also be used to overwrite razzle's server config, right?

**Comment by jaredpalmer** [comment]
That’s what it does. Only important parts tha must be kept is how things are rendered. Ther rest can be altered. Express is optional, you could use koa or hapi or whatevs

**Comment by dav-is** [comment]
Honestly I’m waiting for the razzle plugin where I hope there’s lots of customization hooks. I’ve already overwritten _doc, _app, client, and server just to add csp and jss. Capable but it feels so messy right now

**Comment by jaredpalmer** [comment]
I’m leaning toward just making this a library and removing the build stuff entirely.
