### ISSUE TITLE
Client-side subrouting with top level component (Navigation for example).

### ISSUE THREAD

**Issue by MatthiasMargot** [jaredpalmer/after.js#57]
I've tried creating client-side subroutes like in a fully client-side rendered application with RR4 but After.js seems to be ignorant about any components not defined in `_routes.js` since only telling React about the components causes After to not even download them and those route pages just display blank. It seems that server-side pre-rendered routing triggers a complete wipe of the root content. My goal with this is to have control over page transition animations and not lose client-side state. If there's a simple solution to having control over partially updating the page based on client-side routes(simplest use case would be for navigation). Another question that falls into this category is: can I have my NavLinks defined in only one component that simply doesn't get wiped on route-change?

I'd be really happy if someone could point me in the direction that I'm failing to see. (basically looking for easy alternative to Next.js regarding this problem)

**Comment by frol** [comment]
Can you share your code? It seems that README covers this use-case and it should work: https://github.com/jaredpalmer/after.js#parameterized-routing
