### ISSUE TITLE
Component rendering twice, once without initialProps

### ISSUE THREAD

**Issue by dav-is** [jaredpalmer/after.js#68]
You can replicate with the GraphQL example by loading / and navigating to /posts on the client.

Order of occurrences:
Initial props are fetched
static getInitialProps() on WithData is called
render WithData (without props)
ERROR required prop missing
render WithData (with props)

This leads me to believe it's an issue with _app.js and/or routing

**Comment by mb-jenks** [comment]
@dav-is did this ever get resolved or did you find a work around? I'm seeing the same issue.

**Comment by nimaa77** [comment]
> @dav-is did this ever get resolved or did you find a work around? I'm seeing the same issue.

Hello @dav-is, it’s fixed in #251 .

You can install After.js from master branch or wait until new version get released.

**Comment by mb-jenks** [comment]
Thanks for the quick help!
