### ISSUE TITLE
"Expected server HTML to contain..." warning in console

### ISSUE THREAD

**Issue by howells** [jaredpalmer/after.js#72]
I appreciate this probably isn't an issue with after.js but I can't find a definitive way to resolve it: every once in a while, I get this kind of error in console - 

`Warning: Expected server HTML to contain a matching text node for "Viewport height: " in <p>.`

Once I restart after, it'll work correctly, but then eventually appear again. Where am I going wrong here?

**Comment by jaredpalmer** [comment]
I (think) it’s due to an HMR race condition between server and client. It can be ignored.
