### ISSUE TITLE
getInitialProps not fetching on page refresh

### ISSUE THREAD

**Issue by jforaker** [jaredpalmer/after.js#79]
### Great project!  👍   
Some questions:
Seems like `static async getInitialProps` only gets called when using a Link to access the route. 

For example If you refresh on the /about route, you will see the page gets stuck on "Loading..." and nothing is ssr'd when you view source:
https://after-examples-basic-wycoflvnsg.now.sh/  

Am I misunderstanding the framework? Should data returned from `getInitialProps` get server side rendered? The docs lead me to believe yes, but this isnt working as expected:

```javascript
import React from 'react';
import { NavLink } from 'react-router-dom';

class About extends React.Component {
  static async getInitialProps({ req, res, match }) {
    const hn = await fetch('https://node-hnapi.herokuapp.com/news');
    const stuff = await hn.json();
    return { stuff };
  }

  render() {
    return (
      <div>
        <NavLink to="/">Home</NavLink>
        <NavLink to="/about">About</NavLink>
        <h1>About</h1>
        <pre>
          {this.props.stuff
            ? this.props.stuff.map(item => <p key={item.id}>{item.title}</p>)
            : 'Loading...'}
        </pre>
      </div>
    );
  }
}

export default About;

```

Any info appreciated, thanks!  And keep up the good work 👍

**Comment by jbsmith731** [comment]
@jforaker I could be wrong but I don't think `fetch` will work on the server. I was able to fetch the data on both the client and server using [isomorphic-fetch].(https://www.npmjs.com/package/isomorphic-fetch)

```javascript
import React from 'react';
import { NavLink } from 'react-router-dom';
require('es6-promise').polyfill();
require('isomorphic-fetch');

class About extends React.Component {
  static async getInitialProps({ req, res, match }) {
    const hn = await fetch('https://node-hnapi.herokuapp.com/news');
    const stuff = await hn.json();
    return { stuff };
  }

  render() {
    return (
      <div>
        <NavLink to="/">Home</NavLink>
        <NavLink to="/about">About</NavLink>
        <h1>About</h1>
        <pre>
          {this.props.stuff
            ? this.props.stuff.map(item => <p key={item.id}>{item.title}</p>)
            : 'Loading...'}
        </pre>
      </div>
    );
  }
}

export default About;
```

**Comment by jaredpalmer** [comment]
@jbsmith731 want to submit a PR to modify polyfill.js with isomorphic fetch?

**Comment by jforaker** [comment]
Yep! That fixed it. Good call @jbsmith731 🎉  
I'll close and create a separate issue for the polyfill. 
https://github.com/jaredpalmer/after.js/issues/82
