### ISSUE TITLE
getInitialProps only working on refresh

### ISSUE THREAD

**Issue by fredrik-sogaard** [jaredpalmer/after.js#86]
I've made a clean setup of the [with-afterjs](https://github.com/jaredpalmer/razzle/tree/master/examples/with-afterjs) example from Razzle, and I can't get `getInitialProps` to work properly.

With this code the `whatever` prop is only present on first load or refresh of the / route. 
```
class Home extends Component {
  static async getInitialProps({ req, res, match, history, location, ...ctx }) {
    return { whatever: 'stuff' };
  }

  render() {
    return (
      <div className="Home">
        <div className="Home-header">
          <img src={logo} className="Home-logo" alt="logo" />
          <h2>Welcome to After.js! {this.props.whatever}</h2>
        </div>
        <p className="Home-intro">
          To get started, edit <code>src/Home.js</code> or{' '}
          <code>src/About.js</code>and save to reload.
        </p>
        <Link to="/about">About -></Link>
      </div>
    );
  }
}
```
Here's a live example: https://razzle-examples-with-afterjs-ktjnqfcclv.now.sh/ 
Try navigating to /about and back and notice the prop disappear.

(The previous version of After.js (not a Razzle plugin) worked without problems, so I'm wondering if it has something to do about Razzle?)

**Comment by jaredpalmer** [comment]
Probably just a mistake on my part. I’m waiting to board a train I’ll be on for the next several hours. Will try to take a look in like 30min. Shouldn’t be too tough to debug tho. I think the issue is in src/After.js’s componentWillReceiveProps. Specifically when I spread ...rest to loadInitalProps. That messed me up once in the past.

**Comment by fredrik-sogaard** [comment]
Thanks!

**Comment by AnsonT** [comment]
This still appears to be happening with 1.3.1. The basic example Home.js only gets the 'stuff' prop when refreshed from the client side.
