### ISSUE TITLE
Home component renders on every route?

### ISSUE THREAD

**Issue by fredrik-sogaard** [jaredpalmer/after.js#88]
I noticed when I put a simple console.log on both the Home component and the About component in the example, the Home component renders right before I navigate to /about (or other routes). Is this expected behaviour? Does not happen on a refresh of a single route.

Check live example here (open the console): https://razzle-examples-with-afterjs-uzeclkcyeh.now.sh/

**Comment by fredrik-sogaard** [comment]
I'm still seeing this behaviour, which is different from the pre-Razzle version of After.js.

This is pre-Razzle: https://cl.ly/0v3u0g0w2U3A
The route changes immediately and waits for the timeout in getInitialProps.

This is with the Razzle version: https://cl.ly/0E2K3C3s0A0K
The current route waits for the timeout in getInitialProps and _then_ navigates (which triggers the re-render I first reported).

Exact same code on both examples:
```
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))

class Home extends React.Component {
  static getInitialProps() {
    return sleep(5000).then(() => ({ stuff: 'hello' }))
  }

  render() {
    console.log('Home render')
    return (
      <div className="page">
        <img className="logo" src={logo} alt="After.js Logo" />
        <NavLink to="/">Home (5 sec getInitialProps timeout)</NavLink>
        <NavLink to="/about">About (1 sec getInitialProps timeout)</NavLink>
        <h1>Home (pre-Razzle)</h1>
        <p>Click the button to prefetch data for the About page</p>
        <button onClick={() => this.props.prefetch('/about')}>Prefetch Data!</button>

        <pre>data: {this.props.stuff ? this.props.stuff : 'Loading...'}</pre>
      </div>
    )
  }
}
```

I've tried both ` static getInitialProps()` and ` static await getInitialProps()` with the same result. Any ideas?

**Comment by fredrik-sogaard** [comment]
If I remove `location={previousLocation || location}` in https://github.com/jaredpalmer/after.js/blob/c4266a12daff227a6f4f083e96823002801eb6f6/src/After.tsx#L60 I get the behaviour I expect, but I'm not sure if there are any downsides to this?

Sorry for all the questions!

**Comment by jaredpalmer** [comment]
Yeah this is what needs to be removed
