### ISSUE TITLE
Props missing from After TypeScript declaration

### ISSUE THREAD

**Issue by corydeppen** [jaredpalmer/after.js#97]
When trying to use the `After` component in a TypeScript app, I see an error `Property 'data' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<any, never>, ComponentState>> & Rea...'.`

```ts
ensureReady(routes).then(data =>
  hydrate(
    <BrowserRouter>
      <After data={data} routes={routes} />
    </BrowserRouter>,
    document.getElementById('root')
  )
);
```

This appears to be due to the generated declaration for `After`:

```ts
export declare const After: React.ComponentClass<Pick<any, never>>;
```

By specifying the component props (as opposed to `any`) when the `After` class is defined, the generated declaration includes the props to pick from:

```ts
export declare const After: React.ComponentClass<Pick<Props & RouteComponentProps<any>, "data" | "routes">>;
```

I don't mind submitting a PR if you're okay with this change.

**Comment by jaredpalmer** [comment]
It should have output any, any. The reason is that this allows users that may need to pass more context through to After.js and all routes can do so.

**Comment by jaredpalmer** [comment]
Feel free to submit a PR

**Comment by corydeppen** [comment]
Based on microsoft/typescript#21972, I'm not sure how to proceed. Assuming the generated declaration won't allow `data`, `routes`, and user-defined props to be passed, it seems to suggest it's not possible (at the moment, at least) to use After and TypeScript in strict mode. Thoughts?

**Comment by stepanh** [comment]
+1
@jaredpalmer , could you please create an example of After with TypeScript (and maybe styled-components)? I got server.ts sort of working, but I cannot get past this issue.

**Comment by jaredpalmer** [comment]
Should we just relax after types to any, any?

**Comment by corydeppen** [comment]
Considering the `Afterparty` class is already using `any` for the type of props, I don't know that it can be any more relaxed, right? Based on the [conversation in 21972](https://github.com/Microsoft/TypeScript/issues/21972#issuecomment-366395841), it doesn't look like using a string index signature for a props field to allow custom props beyond `data` and `routes` is an option when using `withRouter`, so I'm at a loss for what the options are at this point. I'm kind of hopeful there might be a slightly different way to type `withRouter` that wouldn't use `Pick`.

**Comment by stepanh** [comment]
This seems to work OK (I had no luck with keeping Pick, but then I'm new to TS):
```
// in After.d.ts

// either
export declare const After: React.ComponentClass<any>;
// or
export declare const After: React.ComponentClass<{data: any, routes: any, [other: string]:any}>;
```

Would it be helpful if I share the (incomplete) example project I have so far (Razzle + TypeScript + styled-components + After.js)?

**Comment by HofmannZ** [comment]
The TypeScript boiler seems to be quite out of date anyhow. If get some time of I will try to make an improved one, any want to help?

**Comment by worudso** [comment]
https://github.com/jaredpalmer/razzle/pull/585
I'm working on typescript example and stuck in this issue.
