### ISSUE TITLE
Create top-level navigation in after.js

### ISSUE THREAD

**Issue by Matt-Owens** [jaredpalmer/after.js#98]
Hi, this worked fine on old version of After.js but as I re-arrange things to work with new version it seems to have broken.  Trying to have a top-level navigation/layout file as follows:

 client.js
```
ensureReady(routes).then(data =>
  hydrate(
    <BrowserRouter>
      <Navigation>
        <After data={data} routes={routes} />
      </Navigation>
    </BrowserRouter>,
    document.getElementById('root')
  )
) 
```

Navigation.js
```
 render() {
    return (
      <div>
        <div className="nav">
            <h2 className="nav--toggle">Navigation</h2>
        </div>

        <div>
          {this.props.children}
        </div>
      </div>
    );
  } 
```

This is not working.  Getting a console error:
` proxyConsole.js:54 Warning: Expected server HTML to contain a matching <h2> in </div>
`
Also Navigation is not rendering in DOM where expected.  Am I doing something wrong here?

**Comment by jaredpalmer** [comment]
The error is because your server and client are not rendering the same react components. In a custom `document.js` you can safely wrap the `After` component like so...

```js
import React from 'react';
import { AfterRoot, AfterData } from '@jaredpalmer/after';

export default class Document extends React.Component {
  static getInitialProps({ assets, data, renderPage }) {
    const page = renderPage(After => props => <><Navigation /><After {...props} /></>)
    return { assets, data, ...page };
  }
 // same a default
}
```

**Comment by Matt-Owens** [comment]
@jaredpalmer Wow, thanks for the super quick response.  I incorporated your advice but it seems like my custom Document is not being recognized.  Any idea why? I made sure to add my document as the documentation shows..

server.js
```
      const html = await render({
        req,
        res,
        Document: MyDocument,
        routes,
        assets,
      });
```

Document.js
```
  static getInitialProps({ assets, data, renderPage }) {
    const page = renderPage(After => props => <Navigation><After {...props}/></Navigation>)
    console.log('get')
    return { assets, data, ...page };
  }
```

None of my console.logs in Document.js are firing, etc.

Again, thanks for your help here.  Loving working with after.

**Comment by jaredpalmer** [comment]
I think i forgot to update docs and renamed it lowercase `document`

**Comment by Matt-Owens** [comment]
Just noticed that and was hoping I'd edit my comment before you replied.  You're just too fast.  Thanks!

**Comment by corydeppen** [comment]
If I understand this correctly, this would mean anyone wanting to utilize a common layout would need to maintain the markup in both a custom `Document` component as well as when `hydrate` is called in the `client` module, right?

**Comment by Matt-Owens** [comment]
@corydeppen Yeah, I believe that's correct.
